-- 用户核心表。参照 mh51-php 的 Mongo `user` 文档翻译为 PostgreSQL 关系表。
-- +goose Up
CREATE TABLE users (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          varchar(64)  NOT NULL DEFAULT '',       -- 内部唯一用户名
    nickname          varchar(64)  NOT NULL DEFAULT '',       -- 昵称
    phone             varchar(32)  NOT NULL DEFAULT '',       -- 手机号
    country_code      varchar(8)   NOT NULL DEFAULT '',       -- 国家区号
    password          varchar(128) NOT NULL DEFAULT '',       -- 密码(哈希)
    slat              varchar(64)  NOT NULL DEFAULT '',       -- 盐

    -- 设备(游客登录)
    device_id         varchar(128) NOT NULL DEFAULT '',       -- 设备编号
    device_type       varchar(32)  NOT NULL DEFAULT '',       -- 设备类型
    device_version    varchar(32)  NOT NULL DEFAULT '',       -- 设备版本
    device_ext        varchar(64)  NOT NULL DEFAULT '',       -- TF 名称等

    -- 资料
    img               varchar(255) NOT NULL DEFAULT '',       -- 头像
    bg_img            varchar(255) NOT NULL DEFAULT '',       -- 背景图
    signature         varchar(255) NOT NULL DEFAULT '',       -- 个性签名(原 sing)
    sex               smallint     NOT NULL DEFAULT 0,        -- 性别 1男 2女
    level             int          NOT NULL DEFAULT 0,        -- 用户等级
    tag               jsonb        NOT NULL DEFAULT '[]',     -- 用户标签数组

    -- 资产
    balance           numeric(14,2) NOT NULL DEFAULT 0,       -- 可用余额(金币)
    credit            numeric(14,2) NOT NULL DEFAULT 0,       -- 可用积分
    gift_count        numeric(14,2) NOT NULL DEFAULT 0,       -- 累计收益
    money_count       numeric(14,2) NOT NULL DEFAULT 0,       -- 累计充值
    send_count        numeric(14,2) NOT NULL DEFAULT 0,       -- 累计送出
    has_buy           smallint     NOT NULL DEFAULT 0,        -- 是否已购买
    rights            jsonb        NOT NULL DEFAULT '{}',     -- 权利(原 right, 保留字改名)
    withdraw_info     jsonb        NOT NULL DEFAULT '{}',     -- 上次提现信息

    -- 用户组 / VIP
    group_id          bigint       NOT NULL DEFAULT 0,        -- 用户组
    group_name        varchar(64)  NOT NULL DEFAULT '',       -- 用户组名称
    group_rate        int          NOT NULL DEFAULT 0,        -- 用户折扣
    group_start_time  bigint       NOT NULL DEFAULT 0,        -- 组开始(epoch)
    group_end_time    bigint       NOT NULL DEFAULT 0,        -- 组结束(epoch)

    -- 关系 / 推广
    parent_id         bigint       NOT NULL DEFAULT 0,        -- 推荐人编号
    parent_name       varchar(64)  NOT NULL DEFAULT '',       -- 推荐人
    channel_name      varchar(64)  NOT NULL DEFAULT '',       -- 渠道
    share_num         int          NOT NULL DEFAULT 0,        -- 分享人数
    fans              int          NOT NULL DEFAULT 0,        -- 粉丝数
    follow            int          NOT NULL DEFAULT 0,        -- 关注数

    -- 地域
    country           varchar(64)  NOT NULL DEFAULT '',
    province          varchar(64)  NOT NULL DEFAULT '',
    city              varchar(64)  NOT NULL DEFAULT '',
    location          varchar(128) NOT NULL DEFAULT '',
    register_area     varchar(128) NOT NULL DEFAULT '',
    is_china          smallint     NOT NULL DEFAULT 1,        -- 是否中国用户

    -- 状态
    is_disabled       smallint     NOT NULL DEFAULT 0,        -- 是否禁用 1是 0否
    error_msg         varchar(255) NOT NULL DEFAULT '',       -- 禁用原因
    is_system         smallint     NOT NULL DEFAULT 0,        -- 是否系统生成

    -- 登录 / 注册轨迹
    register_at       timestamptz,                            -- 注册时间
    register_date     int          NOT NULL DEFAULT 0,        -- 注册日(YYYYMMDD)
    register_ip       varchar(64)  NOT NULL DEFAULT '',
    login_num         int          NOT NULL DEFAULT 0,        -- 登录次数
    last_login_at     timestamptz,                            -- 最后登录时间(原 last_at)
    last_date         int          NOT NULL DEFAULT 0,        -- 最后登录日
    last_ip           varchar(64)  NOT NULL DEFAULT '',

    created_at        timestamptz  NOT NULL DEFAULT now(),
    updated_at        timestamptz  NOT NULL DEFAULT now(),
    deleted_at        timestamptz                             -- 软删除(GoFrame 约定)
);

CREATE UNIQUE INDEX uk_users_username ON users (username) WHERE deleted_at IS NULL;
CREATE INDEX idx_users_phone      ON users (phone);
CREATE INDEX idx_users_device_id  ON users (device_id);
CREATE INDEX idx_users_parent_id  ON users (parent_id);
CREATE INDEX idx_users_group_id   ON users (group_id);
CREATE INDEX idx_users_created_at ON users (created_at);

COMMENT ON TABLE users IS '用户主表';

-- +goose Down
DROP TABLE IF EXISTS users;
