-- 资产: 充值套餐/订单、VIP套餐/记录。
-- +goose Up
CREATE TABLE recharge_package (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           bigint       NOT NULL DEFAULT 1,
    name       varchar(64)   NOT NULL DEFAULT '',
    amount     numeric(10,2) NOT NULL DEFAULT 0,   -- 现金价(元)
    coin       numeric(14,2) NOT NULL DEFAULT 0,   -- 到账金币
    bonus      numeric(14,2) NOT NULL DEFAULT 0,   -- 赠送金币
    sort       int           NOT NULL DEFAULT 0,
    status     smallint      NOT NULL DEFAULT 1,   -- 1上架 0下架
    created_at timestamptz   NOT NULL DEFAULT now()
);
COMMENT ON TABLE recharge_package IS '充值套餐';

CREATE TABLE recharge_order (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           bigint       NOT NULL DEFAULT 1,
    order_no   varchar(64)   NOT NULL,
    user_id    bigint        NOT NULL,
    package_id bigint        NOT NULL DEFAULT 0,
    amount     numeric(10,2) NOT NULL DEFAULT 0,
    coin       numeric(14,2) NOT NULL DEFAULT 0,
    status     smallint      NOT NULL DEFAULT 0,   -- 0待支付 1已支付 -1取消
    pay_at     timestamptz,
    created_at timestamptz   NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_recharge_order_no ON recharge_order (order_no);
CREATE INDEX idx_recharge_order_user ON recharge_order (user_id, created_at);
COMMENT ON TABLE recharge_order IS '充值订单';

CREATE TABLE vip_package (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           bigint       NOT NULL DEFAULT 1,
    name       varchar(64)   NOT NULL DEFAULT '',
    days       int           NOT NULL DEFAULT 0,   -- 时长(天)
    price      numeric(14,2) NOT NULL DEFAULT 0,   -- 金币价
    group_id   bigint        NOT NULL DEFAULT 0,   -- 对应用户组
    sort       int           NOT NULL DEFAULT 0,
    status     smallint      NOT NULL DEFAULT 1,
    created_at timestamptz   NOT NULL DEFAULT now()
);
COMMENT ON TABLE vip_package IS 'VIP套餐';

CREATE TABLE vip_log (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           bigint       NOT NULL DEFAULT 1,
    user_id    bigint        NOT NULL,
    package_id bigint        NOT NULL DEFAULT 0,
    days       int           NOT NULL DEFAULT 0,
    price      numeric(14,2) NOT NULL DEFAULT 0,
    start_at   bigint        NOT NULL DEFAULT 0,   -- epoch
    end_at     bigint        NOT NULL DEFAULT 0,   -- epoch
    created_at timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_vip_log_user ON vip_log (user_id, created_at);
COMMENT ON TABLE vip_log IS 'VIP开通记录';

-- 示例套餐
INSERT INTO recharge_package (name, amount, coin, bonus, sort) VALUES
    ('6元档', 6, 60, 0, 1),
    ('30元档', 30, 300, 30, 2),
    ('98元档', 98, 980, 200, 3);
INSERT INTO vip_package (name, days, price, group_id, sort) VALUES
    ('月卡', 30, 300, 1, 1),
    ('季卡', 90, 800, 1, 2);

-- +goose Down
DROP TABLE IF EXISTS vip_log;
DROP TABLE IF EXISTS vip_package;
DROP TABLE IF EXISTS recharge_order;
DROP TABLE IF EXISTS recharge_package;
