-- 私信: 会话(每人各存一份) + 消息。
-- +goose Up
CREATE TABLE chat_conversation (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           bigint       NOT NULL DEFAULT 1,
    user_id      bigint       NOT NULL,             -- 会话归属人
    peer_id      bigint       NOT NULL,             -- 对方
    last_content varchar(500) NOT NULL DEFAULT '',
    last_at      timestamptz,
    unread       int          NOT NULL DEFAULT 0,
    deleted      smallint     NOT NULL DEFAULT 0,   -- 1 该用户已删会话
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_chat_conv ON chat_conversation (user_id, peer_id);
CREATE INDEX idx_chat_conv_list ON chat_conversation (user_id, deleted, last_at);
COMMENT ON TABLE chat_conversation IS '私信会话(每用户一份)';

CREATE TABLE chat_message (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           bigint       NOT NULL DEFAULT 1,
    from_id    bigint      NOT NULL,
    to_id      bigint      NOT NULL,
    content    text        NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_chat_msg_from ON chat_message (from_id, id);
CREATE INDEX idx_chat_msg_to   ON chat_message (to_id, id);
COMMENT ON TABLE chat_message IS '私信消息';

-- +goose Down
DROP TABLE IF EXISTS chat_message;
DROP TABLE IF EXISTS chat_conversation;
