-- 用户组/等级定义表(B4)。users 表的 group_* 为快照字段, 本表是定义源。
-- +goose Up
CREATE TABLE user_group (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    name       varchar(64)  NOT NULL DEFAULT '',
    rate       int          NOT NULL DEFAULT 100,   -- 折扣(%), 100=无折扣
    rights     jsonb        NOT NULL DEFAULT '{}',  -- 权益配置
    remark     varchar(255) NOT NULL DEFAULT '',
    sort       int          NOT NULL DEFAULT 0,
    status     smallint     NOT NULL DEFAULT 1,     -- 1启用 0停用
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);
COMMENT ON TABLE user_group IS '用户组/等级定义';

-- +goose Down
DROP TABLE IF EXISTS user_group;
