-- 用户相关卫星表。参照 mh51-php 各 User* 集合翻译。
-- +goose Up

-- 关注关系(user_id 关注 home_id)
CREATE TABLE user_follow (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL,                     -- 关注人
    home_id     bigint NOT NULL,                     -- 被关注人
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_user_follow ON user_follow (user_id, home_id);
CREATE INDEX idx_user_follow_home ON user_follow (home_id);
COMMENT ON TABLE user_follow IS '用户关注关系';

-- 兑换码(用户组/金币)
CREATE TABLE user_code (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(64)  NOT NULL DEFAULT '',
    code        varchar(64)  NOT NULL DEFAULT '',     -- 兑换码
    code_key    varchar(64)  NOT NULL DEFAULT '',     -- 码 key
    type        varchar(16)  NOT NULL DEFAULT '',     -- group / point
    object_id   bigint       NOT NULL DEFAULT 0,      -- 用户组或金币资源 id
    add_num     int          NOT NULL DEFAULT 0,      -- 增加数量(天数/金币)
    can_use_num int          NOT NULL DEFAULT 1,      -- 可用次数
    used_num    int          NOT NULL DEFAULT 0,      -- 已用次数
    status      smallint     NOT NULL DEFAULT 0,      -- 0未使用 1已使用 -1作废
    expired_at  bigint       NOT NULL DEFAULT 0,      -- 过期(epoch, 0不过期)
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_user_code_code ON user_code (code);
COMMENT ON TABLE user_code IS '兑换码';

-- 兑换码使用记录
CREATE TABLE user_code_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_id     bigint       NOT NULL DEFAULT 0,
    code        varchar(64)  NOT NULL DEFAULT '',
    code_key    varchar(64)  NOT NULL DEFAULT '',
    name        varchar(64)  NOT NULL DEFAULT '',
    type        varchar(16)  NOT NULL DEFAULT '',
    object_id   bigint       NOT NULL DEFAULT 0,
    user_id     bigint       NOT NULL DEFAULT 0,
    username    varchar(64)  NOT NULL DEFAULT '',
    add_num     int          NOT NULL DEFAULT 0,
    created_at  timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_user_code_log_user ON user_code_log (user_id);
CREATE INDEX idx_user_code_log_code ON user_code_log (code_id);
COMMENT ON TABLE user_code_log IS '兑换码使用记录';

-- 每月签到(days 存当月已签日期)
CREATE TABLE user_sign (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL,
    year_month  int          NOT NULL,                -- 归属月(YYYYMM)
    days        jsonb        NOT NULL DEFAULT '[]',   -- 当月签到日 [1,2,3]
    exchanges   jsonb        NOT NULL DEFAULT '[]',   -- 兑换情况
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_user_sign ON user_sign (user_id, year_month);
COMMENT ON TABLE user_sign IS '用户每月签到';

-- 任务定义
CREATE TABLE user_task (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(64)  NOT NULL DEFAULT '',
    type        varchar(32)  NOT NULL DEFAULT '',     -- 任务类型
    description varchar(255) NOT NULL DEFAULT '',
    max_num     int          NOT NULL DEFAULT 1,      -- 单日最大次数
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);
COMMENT ON TABLE user_task IS '任务定义';

-- 任务完成记录
CREATE TABLE user_task_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL,
    task_id     bigint       NOT NULL DEFAULT 0,
    type        varchar(32)  NOT NULL DEFAULT '',
    num         int          NOT NULL DEFAULT 1,      -- 当次完成数
    log_date    int          NOT NULL DEFAULT 0,      -- 完成日(YYYYMMDD, 便于按日限次)
    created_at  timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_user_task_log_user_date ON user_task_log (user_id, log_date);
COMMENT ON TABLE user_task_log IS '任务完成记录';

-- 余额流水(金币充值/消费/收益的统一账本 —— 新增设计, 便于对账)
CREATE TABLE user_balance_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint        NOT NULL,
    direction   smallint      NOT NULL,               -- 1收入 2支出
    scene       varchar(32)   NOT NULL DEFAULT '',    -- recharge/consume/gift/exchange/task...
    amount      numeric(14,2) NOT NULL DEFAULT 0,     -- 变动额(正数)
    balance_before numeric(14,2) NOT NULL DEFAULT 0,
    balance_after  numeric(14,2) NOT NULL DEFAULT 0,
    ref_id      varchar(64)   NOT NULL DEFAULT '',    -- 关联订单/业务号
    remark      varchar(255)  NOT NULL DEFAULT '',
    created_at  timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_user_balance_log_user ON user_balance_log (user_id, created_at);
COMMENT ON TABLE user_balance_log IS '用户余额流水账本';

-- +goose Down
DROP TABLE IF EXISTS user_balance_log;
DROP TABLE IF EXISTS user_task_log;
DROP TABLE IF EXISTS user_task;
DROP TABLE IF EXISTS user_sign;
DROP TABLE IF EXISTS user_code_log;
DROP TABLE IF EXISTS user_code;
DROP TABLE IF EXISTS user_follow;
