-- 后台管理员 / 角色 / 权限 / 操作日志。
-- +goose Up
CREATE TABLE admin_role (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    name       varchar(64) NOT NULL DEFAULT '',
    code       varchar(64) NOT NULL DEFAULT '',    -- 角色标识, superadmin 为超管
    remark     varchar(255) NOT NULL DEFAULT '',
    status     smallint    NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE admin_role IS '后台角色';

CREATE TABLE admin_user (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       bigint      NOT NULL DEFAULT 1,
    username      varchar(64) NOT NULL DEFAULT '',
    password      varchar(64) NOT NULL DEFAULT '',   -- md5(pwd+salt)
    salt          varchar(32) NOT NULL DEFAULT '',
    nickname      varchar(64) NOT NULL DEFAULT '',
    role_id       bigint      NOT NULL DEFAULT 0,
    status        smallint    NOT NULL DEFAULT 1,     -- 1启用 0禁用
    last_login_at timestamptz,
    last_ip       varchar(64) NOT NULL DEFAULT '',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_admin_user ON admin_user (site_id, username);
COMMENT ON TABLE admin_user IS '后台管理员';

-- Casbin 策略表(标准结构, 供后续 RBAC 使用)
CREATE TABLE casbin_rule (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ptype varchar(100) NOT NULL DEFAULT '',
    v0    varchar(100) NOT NULL DEFAULT '',
    v1    varchar(100) NOT NULL DEFAULT '',
    v2    varchar(100) NOT NULL DEFAULT '',
    v3    varchar(100) NOT NULL DEFAULT '',
    v4    varchar(100) NOT NULL DEFAULT '',
    v5    varchar(100) NOT NULL DEFAULT ''
);
COMMENT ON TABLE casbin_rule IS 'Casbin 权限策略';

CREATE TABLE admin_log (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    admin_id   bigint      NOT NULL DEFAULT 0,
    username   varchar(64) NOT NULL DEFAULT '',
    method     varchar(16) NOT NULL DEFAULT '',
    path       varchar(255) NOT NULL DEFAULT '',
    ip         varchar(64) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_admin_log_admin ON admin_log (admin_id, created_at);
COMMENT ON TABLE admin_log IS '后台操作日志';

-- 种子: 超管角色 + 超管账号(admin / admin123)
INSERT INTO admin_role (name, code, remark) VALUES ('超级管理员', 'superadmin', '拥有全部权限');
INSERT INTO admin_user (username, password, salt, nickname, role_id)
    VALUES ('admin', '05fc7848ada71ded3dc8e6552e09f8b3', 'N8sZ1qKt', '超级管理员', 1);

-- +goose Down
DROP TABLE IF EXISTS admin_log;
DROP TABLE IF EXISTS casbin_rule;
DROP TABLE IF EXISTS admin_user;
DROP TABLE IF EXISTS admin_role;
