-- 用户分享记录表。
-- +goose Up
CREATE TABLE user_share_log (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           bigint       NOT NULL DEFAULT 1,
    user_id    bigint      NOT NULL,
    type       varchar(32) NOT NULL DEFAULT '',   -- 分享类型: app/poster/link/invite...
    target_id  bigint      NOT NULL DEFAULT 0,     -- 分享对象(帖子/视频id, 可选)
    channel    varchar(32) NOT NULL DEFAULT '',    -- 渠道: wechat/qq/moments...
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_user_share_log_user ON user_share_log (user_id, created_at);
COMMENT ON TABLE user_share_log IS '用户分享记录';

-- +goose Down
DROP TABLE IF EXISTS user_share_log;
