-- 菜单驱动 RBAC 已取代 Casbin, 删除遗留策略表。
-- +goose Up
DROP TABLE IF EXISTS casbin_rule;

-- +goose Down
CREATE TABLE casbin_rule (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ptype varchar(100) NOT NULL DEFAULT '',
    v0    varchar(100) NOT NULL DEFAULT '',
    v1    varchar(100) NOT NULL DEFAULT '',
    v2    varchar(100) NOT NULL DEFAULT '',
    v3    varchar(100) NOT NULL DEFAULT '',
    v4    varchar(100) NOT NULL DEFAULT '',
    v5    varchar(100) NOT NULL DEFAULT ''
);
COMMENT ON TABLE casbin_rule IS 'Casbin 权限策略(已废弃, 仅回滚保留)';
