-- P1: 视频管理。
-- +goose Up
CREATE TABLE video (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         bigint       NOT NULL DEFAULT 1,
    title           varchar(128) NOT NULL DEFAULT '',
    description     text         NOT NULL DEFAULT '',
    cover_url       varchar(512) NOT NULL DEFAULT '',
    cover_key       varchar(512) NOT NULL DEFAULT '',
    cover_media_id  bigint       NOT NULL DEFAULT 0,
    source_url      varchar(512) NOT NULL DEFAULT '',
    source_key      varchar(512) NOT NULL DEFAULT '',
    source_media_id bigint       NOT NULL DEFAULT 0,
    duration        int          NOT NULL DEFAULT 0,  -- 秒
    sort            int          NOT NULL DEFAULT 0,
    status          smallint     NOT NULL DEFAULT 0,  -- 0草稿 1上架 2下架
    created_by      bigint       NOT NULL DEFAULT 0,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_video_status_sort ON video (status, sort DESC, id DESC);
CREATE INDEX idx_video_title ON video (title);
COMMENT ON TABLE video IS '视频内容';
COMMENT ON COLUMN video.status IS '0草稿 1上架 2下架';

-- 菜单
INSERT INTO admin_permission (id, parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort) VALUES
 (73, 0, '视频管理', '/video', 'video/index', '', 'lucide:video', 1, 0, 0, 55)
ON CONFLICT (id) DO NOTHING;

-- 接口权限
INSERT INTO admin_permission (id, parent_id, name, route_url, method, is_menu, sort) VALUES
 (74, 73, '视频列表',   '/backend/videos',            'GET',    0, 1),
 (75, 73, '新增视频',   '/backend/videos',            'POST',   0, 2),
 (76, 73, '编辑视频',   '/backend/videos/{id}',       'PUT',    0, 3),
 (77, 73, '删除视频',   '/backend/videos/{id}',       'DELETE', 0, 4),
 (78, 73, '视频上下架', '/backend/videos/{id}/status','PUT',    0, 5)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('admin_permission','id'), (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission WHERE id BETWEEN 73 AND 78;
DROP TABLE IF EXISTS video;
