-- P0: 媒体对象元数据(上传落 MinIO 后的索引)。
-- +goose Up
CREATE TABLE media_object (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      bigint       NOT NULL DEFAULT 1,
    bucket       varchar(128) NOT NULL DEFAULT '',
    object_key   varchar(512) NOT NULL DEFAULT '',
    purpose      varchar(32)  NOT NULL DEFAULT 'image', -- image / cover / video / avatar
    content_type varchar(128) NOT NULL DEFAULT '',
    size         bigint       NOT NULL DEFAULT 0,
    etag         varchar(128) NOT NULL DEFAULT '',
    created_by   bigint       NOT NULL DEFAULT 0,
    created_at   timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_media_object_key ON media_object (bucket, object_key);
CREATE INDEX idx_media_object_purpose ON media_object (purpose, id DESC);
CREATE INDEX idx_media_object_created_by ON media_object (created_by, id DESC);
COMMENT ON TABLE media_object IS '对象存储媒体索引(MinIO/S3)';
COMMENT ON COLUMN media_object.purpose IS '用途: image/cover/video/avatar';

-- 接口权限(挂运营管理 parent_id=7)
INSERT INTO admin_permission (id, parent_id, name, route_url, method, is_menu, sort) VALUES
 (67, 7, '上传媒体', '/backend/media/upload', 'POST', 0, 20)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('admin_permission','id'), (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission WHERE id = 67;
DROP TABLE IF EXISTS media_object;
