-- 分片上传会话(MinIO multipart + 断点续传)。
-- +goose Up
CREATE TABLE media_multipart (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         bigint       NOT NULL DEFAULT 1,
    upload_id       varchar(64)  NOT NULL DEFAULT '',          -- 业务侧会话 ID(UUID)
    minio_upload_id varchar(256) NOT NULL DEFAULT '',          -- MinIO multipart uploadId
    bucket          varchar(128) NOT NULL DEFAULT '',
    object_key      varchar(512) NOT NULL DEFAULT '',
    purpose         varchar(32)  NOT NULL DEFAULT 'video',
    filename        varchar(255) NOT NULL DEFAULT '',
    content_type    varchar(128) NOT NULL DEFAULT '',
    size            bigint       NOT NULL DEFAULT 0,
    part_size       bigint       NOT NULL DEFAULT 0,
    part_count      int          NOT NULL DEFAULT 0,
    status          smallint     NOT NULL DEFAULT 0,           -- 0上传中 1已完成 2已取消
    media_id        bigint       NOT NULL DEFAULT 0,           -- 完成后关联 media_object.id
    created_by      bigint       NOT NULL DEFAULT 0,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_media_multipart_upload_id ON media_multipart (upload_id);
CREATE INDEX idx_media_multipart_status ON media_multipart (status, updated_at DESC);
CREATE INDEX idx_media_multipart_created_by ON media_multipart (created_by, id DESC);
COMMENT ON TABLE media_multipart IS 'MinIO 分片上传会话';
COMMENT ON COLUMN media_multipart.status IS '0上传中 1已完成 2已取消';

INSERT INTO admin_permission (id, parent_id, name, route_url, method, is_menu, sort) VALUES
 (68, 7, '分片上传-初始化', '/backend/media/multipart/init',     'POST', 0, 21),
 (69, 7, '分片上传-预签名', '/backend/media/multipart/presign',  'POST', 0, 22),
 (70, 7, '分片上传-已传列表', '/backend/media/multipart/parts',  'GET',  0, 23),
 (71, 7, '分片上传-合并',   '/backend/media/multipart/complete', 'POST', 0, 24),
 (72, 7, '分片上传-取消',   '/backend/media/multipart/abort',    'POST', 0, 25)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('admin_permission','id'), (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission WHERE id BETWEEN 68 AND 72;
DROP TABLE IF EXISTS media_multipart;
