-- 签到(移植自 tianbi checkin): 连续签到 + 阶梯奖励配置。与现有月度 user_sign 并存。
-- +goose Up
CREATE TABLE checkin_reward (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    day_num    int         NOT NULL,              -- 连续第 N 天触发(1~30 周期内)
    user_type  smallint    NOT NULL DEFAULT 0,    -- 0=通用/免费 1=VIP
    gold       bigint      NOT NULL DEFAULT 0,    -- 赠送金币(加到 users.balance)
    vip_days   int         NOT NULL DEFAULT 0,    -- 赠送VIP天数(需VIP系统实际发放)
    status     smallint    NOT NULL DEFAULT 1,    -- 1启用 0停用
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_checkin_reward ON checkin_reward (site_id, day_num, user_type);
COMMENT ON TABLE checkin_reward IS '签到阶梯奖励配置';

CREATE TABLE user_checkin (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id           bigint      NOT NULL DEFAULT 1,
    user_id           bigint      NOT NULL,
    checkin_date      date        NOT NULL,
    continuously_days int         NOT NULL DEFAULT 1,   -- 连续签到天数(快照)
    reward_gold       bigint      NOT NULL DEFAULT 0,   -- 本次发放金币(快照)
    created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_user_checkin ON user_checkin (site_id, user_id, checkin_date);
CREATE INDEX idx_user_checkin_user ON user_checkin (site_id, user_id, checkin_date DESC);
COMMENT ON TABLE user_checkin IS '用户每日签到记录';

-- 示例阶梯(site_id=1): 连续第 1/2/3/5/7 天金币奖励
INSERT INTO checkin_reward (site_id, day_num, user_type, gold, status) VALUES
 (1,1,0,10,1),(1,2,0,20,1),(1,3,0,30,1),(1,5,0,50,1),(1,7,0,100,1);

-- +goose Down
DROP TABLE IF EXISTS user_checkin;
DROP TABLE IF EXISTS checkin_reward;
