-- B7: 系统公告/推送 + 站点键值配置。
-- +goose Up
CREATE TABLE system_notice (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    title      varchar(128) NOT NULL DEFAULT '',
    content    text         NOT NULL DEFAULT '',
    type       varchar(16)  NOT NULL DEFAULT 'notice',  -- notice公告 / push推送
    status     smallint     NOT NULL DEFAULT 1,          -- 1上架 0下线
    created_by bigint       NOT NULL DEFAULT 0,          -- 发布管理员ID
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_system_notice_type ON system_notice (type, status, id);
COMMENT ON TABLE system_notice IS '系统公告/推送';

CREATE TABLE site_config (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    conf_key   varchar(64)  NOT NULL,
    conf_value text         NOT NULL DEFAULT '',
    updated_at timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_site_config_key ON site_config (site_id, conf_key);
COMMENT ON TABLE site_config IS '站点键值配置(后台可改, 前台即时生效)';

-- +goose Down
DROP TABLE IF EXISTS site_config;
DROP TABLE IF EXISTS system_notice;
