-- 兑换码(移植自 tianbi redeemcode): 后台建码, 前台兑换发奖。
-- 与 tianbi 差异: my_service 用户体系当前只有金币(users.balance), card_type 先只启用 1=金币,
-- 字段保留以便将来扩展(2=VIP天数等)。同一用户同一码只能用一次(唯一约束兜底, 同 tianbi)。
-- +goose Up
CREATE TABLE redeem_code (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      bigint       NOT NULL DEFAULT 1,
    name         varchar(64)  NOT NULL DEFAULT '',   -- 兑换码名字/活动名
    code         varchar(32)  NOT NULL,              -- 兑换码本身
    card_type    smallint     NOT NULL DEFAULT 1,    -- 1金币(当前仅支持) 预留: 2VIP天数
    value        int          NOT NULL DEFAULT 0,    -- 可用值: 金币数/天数
    total_times  int          NOT NULL DEFAULT 1,    -- 总可兑换次数
    used_times   int          NOT NULL DEFAULT 0,    -- 已兑换次数
    status       smallint     NOT NULL DEFAULT 1,    -- 1启用 0禁用(次数用完自动置0)
    expired_at   timestamptz  NOT NULL,              -- 过期时间
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (site_id, code)
);
CREATE INDEX idx_redeem_code_status ON redeem_code (site_id, status, expired_at);
COMMENT ON TABLE redeem_code IS '兑换码';

CREATE TABLE redeem_code_record (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    user_id    bigint       NOT NULL,
    code_id    bigint       NOT NULL,
    code       varchar(32)  NOT NULL,
    name       varchar(64)  NOT NULL DEFAULT '',
    card_type  smallint     NOT NULL DEFAULT 1,
    value      int          NOT NULL DEFAULT 0,
    created_at timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (site_id, user_id, code)                  -- 同一用户同一码只能用一次
);
CREATE INDEX idx_rcr_user ON redeem_code_record (site_id, user_id, created_at DESC);
CREATE INDEX idx_rcr_code ON redeem_code_record (site_id, code);
COMMENT ON TABLE redeem_code_record IS '兑换码使用记录';

-- 样板数据: 测试码 WELCOME100(金币100, 可用100次, 2027年过期)
INSERT INTO redeem_code (site_id, name, code, card_type, value, total_times, status, expired_at)
VALUES (1, '新人见面礼', 'WELCOME100', 1, 100, 100, 1, '2027-12-31 23:59:59+08');

-- +goose Down
DROP TABLE IF EXISTS redeem_code_record;
DROP TABLE IF EXISTS redeem_code;
