-- 帖子社区(移植自 tianbi post/community, 精简核心面): UGC 发帖 + 审核 + 引用媒资。
-- 点赞走 user_collect(media_type=2), 评论走 comment(media_type=2)。
-- +goose Up
CREATE TABLE post (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       bigint       NOT NULL DEFAULT 1,
    user_id       bigint       NOT NULL,
    title         varchar(128) NOT NULL,
    content       text         NOT NULL DEFAULT '',
    pics          jsonb        NOT NULL DEFAULT '[]', -- 图片URL数组
    media_id      bigint       NOT NULL DEFAULT 0,    -- 引用媒资(视频id, 0=无)
    view_count    bigint       NOT NULL DEFAULT 0,
    like_count    int          NOT NULL DEFAULT 0,
    comment_count int          NOT NULL DEFAULT 0,
    status        smallint     NOT NULL DEFAULT 0,    -- 0待审 1通过 2拒绝 3用户删除
    reject_reason varchar(255) NOT NULL DEFAULT '',
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_post_feed  ON post (site_id, status, id DESC);
CREATE INDEX idx_post_hot   ON post (site_id, status, like_count DESC, id DESC);
CREATE INDEX idx_post_user  ON post (site_id, user_id, id DESC);
COMMENT ON TABLE post IS '社区帖子(UGC, 需审核)';

-- +goose Down
DROP TABLE IF EXISTS post;
