-- 标签(移植自 tianbi tag): tianbi 按内容类型分散在 mediatag/comicstag/actressphototag/noveltag/postdiscusstag
-- 多个集合, PG 统一为单表 + content_type 列。前台按 content_type 拉取, 后台 CRUD 维护。
-- +goose Up
CREATE TABLE tag (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      bigint       NOT NULL DEFAULT 1,
    content_type smallint     NOT NULL DEFAULT 1,   -- 1影片 2抖音 3动漫 4漫画 5图集 6帖子 7小说
    name         varchar(64)  NOT NULL,
    rank         int          NOT NULL DEFAULT 0,    -- 排序权重(desc, 越大越靠前)
    status       smallint     NOT NULL DEFAULT 1,    -- 1启用 0禁用
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (site_id, content_type, name)
);
CREATE INDEX idx_tag_repo ON tag (site_id, content_type, status, rank DESC, id DESC);
COMMENT ON TABLE tag IS '内容标签(按 content_type 区分影片/漫画/图集等)';

-- 样板数据: site_id=1, 影片(1)/漫画(4)/图集(5) 各若干
INSERT INTO tag (site_id, content_type, name, rank, status) VALUES
    (1, 1, '国产', 100, 1),
    (1, 1, '日韩', 90,  1),
    (1, 1, '欧美', 80,  1),
    (1, 1, '动作', 70,  1),
    (1, 4, '热血', 100, 1),
    (1, 4, '恋爱', 90,  1),
    (1, 4, '玄幻', 80,  1),
    (1, 5, '写真', 100, 1),
    (1, 5, '风景', 90,  1);

-- +goose Down
DROP TABLE IF EXISTS tag;
