-- 收藏/点赞/踩(移植自 tianbi collect): 统一操作表, op_type 区分。
-- 与 tianbi 差异: tianbi 返回完整内容对象, my_service 内容体系尚在迁移中,
-- 列表先返回 content_id, 客户端按需拉详情。
-- +goose Up
CREATE TABLE user_collect (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    user_id    bigint      NOT NULL,
    op_type    smallint    NOT NULL DEFAULT 1,  -- 1收藏 2点赞 3踩
    media_type smallint    NOT NULL DEFAULT 1,  -- 1视频 2帖子(同 tianbi mediaType)
    content_id bigint      NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (site_id, user_id, op_type, media_type, content_id)
);
CREATE INDEX idx_user_collect_list ON user_collect (site_id, user_id, op_type, media_type, created_at DESC);
CREATE INDEX idx_user_collect_content ON user_collect (site_id, op_type, media_type, content_id);
COMMENT ON TABLE user_collect IS '用户收藏/点赞/踩';

-- +goose Down
DROP TABLE IF EXISTS user_collect;
