-- 基础配置(移植自 tianbi ping/config): tianbi 是聚合硬编码大接口,
-- PG 版改为通用 KV 配置表, 后台随时增删配置项, 前台一次拉全量(客户端启动第一个协议)。
-- value 为 jsonb: 支持数字/布尔/字符串/对象, 前台按原始类型返回。
-- +goose Up
CREATE TABLE app_config (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    grp        varchar(32)  NOT NULL DEFAULT 'base',  -- 分组: base/share/contact/switch...
    key        varchar(64)  NOT NULL,
    value      jsonb        NOT NULL DEFAULT 'null',
    remark     varchar(255) NOT NULL DEFAULT '',
    status     smallint     NOT NULL DEFAULT 1,       -- 1启用 0禁用(前台不下发)
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (site_id, key)
);
CREATE INDEX idx_app_config_grp ON app_config (site_id, grp, status);
COMMENT ON TABLE app_config IS '应用基础配置(KV)';

-- 样板数据
INSERT INTO app_config (site_id, grp, key, value, remark, status) VALUES
    (1, 'base',    'app_name',        '"漫隐"',                        '应用名称', 1),
    (1, 'base',    'min_version',     '"1.0.0"',                       '最低支持版本', 1),
    (1, 'base',    'force_update',    'false',                         '是否强制更新', 1),
    (1, 'share',   'share_url',       '"https://example.com/share"',   '分享落地页', 1),
    (1, 'contact', 'admin_tg',        '"@my_admin"',                   '管理员TG', 1),
    (1, 'switch',  'is_open_comment', 'true',                          '是否开放评论', 1),
    (1, 'switch',  'maintenance',     'false',                         '维护开关', 1);

-- +goose Down
DROP TABLE IF EXISTS app_config;
