-- 应用推广(移植自 tianbi ApplicationInfo/StatConfigApp): 推广应用列表 + 下载点击计数。
-- +goose Up
CREATE TABLE application (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      bigint       NOT NULL DEFAULT 1,
    name         varchar(64)  NOT NULL,
    tag          int          NOT NULL DEFAULT 0,    -- 标签
    intro        varchar(255) NOT NULL DEFAULT '',   -- 描述(desc 为 SQL 关键字, 列名用 intro)
    avatar       varchar(500) NOT NULL DEFAULT '',   -- 图标
    download_url varchar(500) NOT NULL DEFAULT '',   -- 通用下载地址
    ios_url      varchar(500) NOT NULL DEFAULT '',
    android_url  varchar(500) NOT NULL DEFAULT '',
    loc_ids      jsonb        NOT NULL DEFAULT '[]', -- 投放位置数组
    rank         int          NOT NULL DEFAULT 0,    -- 排序(desc)
    down_total   bigint       NOT NULL DEFAULT 0,    -- 下载点击次数
    status       smallint     NOT NULL DEFAULT 1,    -- 1上架 0下架
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_application_list ON application (site_id, status, rank DESC, id DESC);
COMMENT ON TABLE application IS '推广应用';

-- 样板数据
INSERT INTO application (site_id, name, intro, avatar, download_url, loc_ids, rank, status) VALUES
    (1, '示例应用A', '样板推广应用', 'https://example.com/a.png', 'https://example.com/a.apk', '[1]', 100, 1),
    (1, '示例应用B', '样板推广应用', 'https://example.com/b.png', 'https://example.com/b.apk', '[1,2]', 90, 1);

-- +goose Down
DROP TABLE IF EXISTS application;
