-- 系统消息(站内信): 后台发布(全员/指定用户), 前台列表+已读标记。
-- 私信对话已由 chat_conversation/chat_message 承载, 本模块只管系统下发。
-- +goose Up
CREATE TABLE sys_message (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    user_id    bigint       NOT NULL DEFAULT 0,   -- 0=全员消息, >0=指定用户
    type       smallint     NOT NULL DEFAULT 1,   -- 1系统通知 2活动 3审核结果...
    title      varchar(128) NOT NULL,
    content    text         NOT NULL DEFAULT '',
    status     smallint     NOT NULL DEFAULT 1,   -- 1发布 0撤回
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_sys_message_list ON sys_message (site_id, status, user_id, created_at DESC);
COMMENT ON TABLE sys_message IS '系统消息(站内信)';

CREATE TABLE sys_message_read (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    user_id    bigint      NOT NULL,
    message_id bigint      NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (site_id, user_id, message_id)
);
COMMENT ON TABLE sys_message_read IS '系统消息已读记录';

-- 样板数据: 一条全员消息
INSERT INTO sys_message (site_id, user_id, type, title, content, status)
VALUES (1, 0, 1, '欢迎使用漫隐', '感谢注册, 祝使用愉快!', 1);

-- +goose Down
DROP TABLE IF EXISTS sys_message_read;
DROP TABLE IF EXISTS sys_message;
