-- 运营配置(移植自 tianbi announcement/jumptab/filterword): 公告 + 跳转位 + 敏感词。
-- +goose Up
CREATE TABLE announcement (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    title      varchar(128) NOT NULL,
    content    text         NOT NULL DEFAULT '',
    text_node  text         NOT NULL DEFAULT '',   -- 富文本内容
    cover      varchar(500) NOT NULL DEFAULT '',   -- 封面
    jump_url   varchar(500) NOT NULL DEFAULT '',   -- 活动跳转地址
    sys_type   varchar(16)  NOT NULL DEFAULT 'app',-- app / h5app
    start_at   timestamptz  NOT NULL DEFAULT now(),-- 生效开始
    end_at     timestamptz  NOT NULL,              -- 生效结束
    status     smallint     NOT NULL DEFAULT 1,    -- 1开启 0关闭
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_announcement_live ON announcement (site_id, status, start_at, end_at);
COMMENT ON TABLE announcement IS '官方公告';

CREATE TABLE jumptab (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       bigint       NOT NULL DEFAULT 1,
    cn_name       varchar(64)  NOT NULL,
    en_name       varchar(64)  NOT NULL DEFAULT '',
    avatar        varchar(500) NOT NULL DEFAULT '',  -- 图标
    link          varchar(500) NOT NULL DEFAULT '',  -- 跳转链接
    pic_jump_link varchar(500) NOT NULL DEFAULT '',  -- 图片跳转链接
    location      int          NOT NULL DEFAULT 1,   -- 位置
    rank          int          NOT NULL DEFAULT 0,   -- 排序(desc)
    status        smallint     NOT NULL DEFAULT 1,   -- 1启用 0禁用
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_jumptab_list ON jumptab (site_id, status, location, rank DESC);
COMMENT ON TABLE jumptab IS '首页跳转位';

CREATE TABLE filter_word (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    word       varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (site_id, word)
);
COMMENT ON TABLE filter_word IS '敏感词';

-- 样板数据
INSERT INTO announcement (site_id, title, content, sys_type, start_at, end_at, status)
VALUES (1, '欢迎公告', '漫隐上线啦', 'app', now(), '2027-12-31 23:59:59+08', 1);
INSERT INTO jumptab (site_id, cn_name, en_name, link, location, rank, status)
VALUES (1, '每日签到', 'Checkin', '/checkin', 1, 100, 1);
INSERT INTO filter_word (site_id, word) VALUES (1, '测试敏感词');

-- +goose Down
DROP TABLE IF EXISTS filter_word;
DROP TABLE IF EXISTS jumptab;
DROP TABLE IF EXISTS announcement;
