-- 评论(移植自 tianbi comment): 树形 parent_id, root_id 反范式化顶层锚点(免递归查询)。
-- +goose Up
CREATE TABLE comment (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id     bigint      NOT NULL DEFAULT 1,
    user_id     bigint      NOT NULL,
    media_type  smallint    NOT NULL DEFAULT 1,  -- 1视频 2帖子 4漫画 7小说
    content_id  bigint      NOT NULL,
    parent_id   bigint      NOT NULL DEFAULT 0,  -- 0=顶层
    root_id     bigint      NOT NULL DEFAULT 0,  -- 顶层评论id(顶层自身为0)
    content     text        NOT NULL,
    like_count  int         NOT NULL DEFAULT 0,
    reply_count int         NOT NULL DEFAULT 0,  -- 仅顶层维护
    status      smallint    NOT NULL DEFAULT 1,  -- 1正常 0隐藏
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_comment_top  ON comment (site_id, media_type, content_id, root_id, id DESC);
CREATE INDEX idx_comment_user ON comment (site_id, user_id, id DESC);
COMMENT ON TABLE comment IS '内容评论(树形)';

-- +goose Down
DROP TABLE IF EXISTS comment;
