-- 意见反馈(移植自 tianbi feedback): 用户提交 + 后台处理。
-- +goose Up
CREATE TABLE feedback (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      bigint       NOT NULL DEFAULT 1,
    user_id      bigint       NOT NULL,
    type         smallint     NOT NULL DEFAULT 1,   -- 1用户反馈 2程序反馈
    problem_type int          NOT NULL DEFAULT 0,   -- 问题类型
    content      text         NOT NULL DEFAULT '',
    pics         jsonb        NOT NULL DEFAULT '[]',-- 图片URL数组
    sys_info     text         NOT NULL DEFAULT '',  -- 客户端/系统信息
    media_id     bigint       NOT NULL DEFAULT 0,   -- 关联视频id
    media_title  varchar(255) NOT NULL DEFAULT '',
    status       smallint     NOT NULL DEFAULT 1,   -- 1处理中 2已处理
    reply        text         NOT NULL DEFAULT '',  -- 后台回复
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_feedback_user   ON feedback (site_id, user_id, created_at DESC);
CREATE INDEX idx_feedback_status ON feedback (site_id, status, created_at DESC);
COMMENT ON TABLE feedback IS '用户意见反馈';

-- +goose Down
DROP TABLE IF EXISTS feedback;
