-- 图集(与漫画同源的付费内容, 但形态更轻)。
-- 与 00036 漫画的关键差异:
--   * 图集没有"章节"这一层, 一套图就是一条记录 → 图片数组直接挂在主表的 pics jsonb 上,
--     省掉 comics_chapter 那样的从表, 读详情只需一次单表查询;
--   * 因为没有章节, "前 N 章免费" 退化为 free_count: 未解锁时只下发 pics 的前 N 张做预览,
--     截断在服务端做, 客户端拿不到剩余图片的 url(付费墙不能靠前端隐藏);
--   * tags 同样用 jsonb + GIN, 付费模型仍是 shared/paywall 的 is_vip / price 两态。
-- +goose Up
CREATE TABLE photo_album (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id     bigint        NOT NULL DEFAULT 1,
    title       varchar(128)  NOT NULL,
    cover       varchar(500)  NOT NULL DEFAULT '',
    intro       varchar(1000) NOT NULL DEFAULT '',
    category    varchar(32)   NOT NULL DEFAULT '',   -- 分类
    tags        jsonb         NOT NULL DEFAULT '[]', -- 标签数组
    is_vip      smallint      NOT NULL DEFAULT 0,    -- 1=VIP专享(与 price 互斥)
    price       numeric(14,2) NOT NULL DEFAULT 0,    -- 金币整套价
    free_count  int           NOT NULL DEFAULT 0,    -- 未解锁时可预览的前 N 张
    pics        jsonb         NOT NULL DEFAULT '[]', -- [{url,width,height}]
    pic_count   int           NOT NULL DEFAULT 0,    -- 冗余总张数, 列表页免解 jsonb
    view_count  bigint        NOT NULL DEFAULT 0,
    buy_count   bigint        NOT NULL DEFAULT 0,
    like_count  bigint        NOT NULL DEFAULT 0,
    rank        int           NOT NULL DEFAULT 0,    -- 人工权重
    status      smallint      NOT NULL DEFAULT 0,    -- 0待上架 1上架 2下架
    publish_id  bigint        NOT NULL DEFAULT 0,    -- 投稿来源用户(0=官方)
    created_at  timestamptz   NOT NULL DEFAULT now(),
    updated_at  timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_photo_list ON photo_album (site_id, status, rank DESC, id DESC);
CREATE INDEX idx_photo_cate ON photo_album (site_id, status, category);
CREATE INDEX idx_photo_tags ON photo_album USING GIN (tags);
COMMENT ON TABLE photo_album IS '图集';

-- 标题 trgm 索引(搜索用; 扩展没装则跳过)
-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm') THEN
        CREATE INDEX IF NOT EXISTS idx_photo_title_trgm ON photo_album USING GIN (title gin_trgm_ops);
    END IF;
END
$$;
-- +goose StatementEnd

-- 样板数据: 一套免费 + 一套付费(price=15, free_count=2), 各 5 张, 便于 e2e 直接跑
INSERT INTO photo_album (site_id, title, cover, intro, category, tags, is_vip, price, free_count, pics, pic_count, rank, status)
VALUES
    (1, '样板图集·免费篇', 'https://example.com/album_free_cover.jpg', '用于 e2e 的免费样板', '写真',
     '["写真","样板"]', 0, 0, 5,
     '[{"url":"https://example.com/album_free_1.jpg","width":1080,"height":1620},
       {"url":"https://example.com/album_free_2.jpg","width":1080,"height":1620},
       {"url":"https://example.com/album_free_3.jpg","width":1080,"height":1620},
       {"url":"https://example.com/album_free_4.jpg","width":1080,"height":1620},
       {"url":"https://example.com/album_free_5.jpg","width":1080,"height":1620}]',
     5, 100, 1),
    (1, '样板图集·付费篇', 'https://example.com/album_paid_cover.jpg', '用于 e2e 的付费样板', '风景',
     '["风景","样板"]', 0, 15, 2,
     '[{"url":"https://example.com/album_paid_1.jpg","width":1080,"height":1620},
       {"url":"https://example.com/album_paid_2.jpg","width":1080,"height":1620},
       {"url":"https://example.com/album_paid_3.jpg","width":1080,"height":1620},
       {"url":"https://example.com/album_paid_4.jpg","width":1080,"height":1620},
       {"url":"https://example.com/album_paid_5.jpg","width":1080,"height":1620}]',
     5, 90, 1);

-- +goose Down
DROP TABLE IF EXISTS photo_album;
