-- 漫画(移植自 tianbi comics + comics_chapter)。
-- Mongo → PG 的取舍:
--   * 章节图片数组 chapter[]{width,high,comicsPic} 是典型的"嵌套且只整体读写" → 用 jsonb 存, 不再拆表;
--   * tags/topics 同理用 jsonb, 需要按标签查时走 GIN 索引;
--   * 付费模型简化为 is_vip / price 两态(见 shared/paywall), free_chapter 控制前 N 章免费。
-- +goose Up
CREATE TABLE comics (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       bigint        NOT NULL DEFAULT 1,
    title         varchar(128)  NOT NULL,
    author        varchar(64)   NOT NULL DEFAULT '',
    cover         varchar(500)  NOT NULL DEFAULT '',
    intro         varchar(1000) NOT NULL DEFAULT '',
    category      varchar(32)   NOT NULL DEFAULT '',   -- 分类
    tags          jsonb         NOT NULL DEFAULT '[]', -- 标签数组
    is_vip        smallint      NOT NULL DEFAULT 0,    -- 1=VIP专享(与 price 互斥)
    price         numeric(14,2) NOT NULL DEFAULT 0,    -- 金币整部价
    free_chapter  int           NOT NULL DEFAULT 1,    -- 前 N 章免费(章节序号 <= N)
    chapter_count int           NOT NULL DEFAULT 0,
    view_count    bigint        NOT NULL DEFAULT 0,
    buy_count     bigint        NOT NULL DEFAULT 0,
    like_count    bigint        NOT NULL DEFAULT 0,
    update_status smallint      NOT NULL DEFAULT 1,    -- 1连载 2完结
    rank          int           NOT NULL DEFAULT 0,    -- 人工权重
    status        smallint      NOT NULL DEFAULT 0,    -- 0待上架 1上架 2下架
    publish_id    bigint        NOT NULL DEFAULT 0,    -- 投稿来源用户(0=官方)
    created_at    timestamptz   NOT NULL DEFAULT now(),
    updated_at    timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_comics_list ON comics (site_id, status, rank DESC, id DESC);
CREATE INDEX idx_comics_cate ON comics (site_id, status, category);
CREATE INDEX idx_comics_tags ON comics USING GIN (tags);
COMMENT ON TABLE comics IS '漫画作品';

CREATE TABLE comics_chapter (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    comics_id  bigint       NOT NULL,
    seq        int          NOT NULL,               -- 章节序号, 从 1 开始
    title      varchar(128) NOT NULL DEFAULT '',
    pics       jsonb        NOT NULL DEFAULT '[]',  -- [{url,width,height}]
    pic_count  int          NOT NULL DEFAULT 0,
    status     smallint     NOT NULL DEFAULT 1,     -- 1上架 0下架
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (site_id, comics_id, seq)
);
CREATE INDEX idx_comics_chapter ON comics_chapter (site_id, comics_id, seq);
COMMENT ON TABLE comics_chapter IS '漫画章节';

-- 标题 trgm 索引(搜索用; 扩展没装则跳过)
-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm') THEN
        CREATE INDEX IF NOT EXISTS idx_comics_title_trgm ON comics USING GIN (title gin_trgm_ops);
    END IF;
END
$$;
-- +goose StatementEnd

-- 样板数据: 一部免费 + 一部付费, 便于 e2e 直接跑
INSERT INTO comics (site_id, title, author, intro, category, tags, is_vip, price, free_chapter, chapter_count, rank, status)
VALUES
    (1, '样板漫画·免费篇', '佚名', '用于 e2e 的免费样板', '热血', '["热血","样板"]', 0, 0,  99, 2, 100, 1),
    (1, '样板漫画·付费篇', '佚名', '用于 e2e 的付费样板', '恋爱', '["恋爱","样板"]', 0, 30, 1,  2, 90,  1);

INSERT INTO comics_chapter (site_id, comics_id, seq, title, pics, pic_count, status)
SELECT 1, c.id, s.seq, '第' || s.seq || '话',
       ('[{"url":"https://example.com/' || c.id || '_' || s.seq || '_1.jpg","width":800,"height":1200}]')::jsonb,
       1, 1
FROM comics c CROSS JOIN (SELECT generate_series(1, 2) AS seq) s
WHERE c.site_id = 1 AND c.title LIKE '样板漫画%';

-- +goose Down
DROP TABLE IF EXISTS comics_chapter;
DROP TABLE IF EXISTS comics;
