-- 提现(移植自 tianbi withdrawal + bankcard)。
-- 与 tianbi 的差异:
--   1. tianbi 余额分 workIncome/promIncome 两池、按固定顺序扣; my_service 统一走 users.balance 单池;
--   2. tianbi 用 Mongo 条件更新做乐观并发; PG 版用「事务 + WHERE 条件更新 + RowsAffected 判定」;
--   3. 提现申请即冻结(扣款并写流水), 拒绝/撤回时原路退款, 保证任何时刻 余额+在途 守恒。
-- 状态机: 1申请中 →2审核通过 →4已打款(终态)
--         1|2 →5已拒绝(退款, 终态)
--         1   →6用户撤回(退款, 终态)
-- +goose Up
CREATE TABLE bank_card (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      bigint       NOT NULL DEFAULT 1,
    user_id      bigint       NOT NULL,
    account_type smallint     NOT NULL DEFAULT 1,   -- 1银行卡 2支付宝 3USDT
    account_name varchar(64)  NOT NULL DEFAULT '',  -- 开户人/实名
    account_no   varchar(64)  NOT NULL,             -- 卡号/账号/地址
    bank_name    varchar(64)  NOT NULL DEFAULT '',  -- 开户行/网络(如 TRC20)
    is_default   smallint     NOT NULL DEFAULT 0,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (site_id, user_id, account_no)           -- 同一用户不可重复添加同一账号
);
CREATE INDEX idx_bank_card_user ON bank_card (site_id, user_id, id DESC);
COMMENT ON TABLE bank_card IS '用户收款账户';

CREATE TABLE withdrawal (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      bigint        NOT NULL DEFAULT 1,
    trade_no     varchar(64)   NOT NULL,               -- 业务单号(幂等键)
    user_id      bigint        NOT NULL,
    amount       numeric(14,2) NOT NULL,               -- 申请提现金额(扣除的余额)
    fee          numeric(14,2) NOT NULL DEFAULT 0,     -- 手续费
    real_amount  numeric(14,2) NOT NULL DEFAULT 0,     -- 实际到账 = amount - fee
    fee_rate     numeric(6,2)  NOT NULL DEFAULT 0,     -- 手续费率(%), 快照
    balance_after numeric(14,2) NOT NULL DEFAULT 0,    -- 冻结后余额快照
    account_info jsonb         NOT NULL DEFAULT '{}',  -- 收款账户快照(卡号/户名/开户行)
    status       smallint      NOT NULL DEFAULT 1,     -- 1申请中 2审核通过 4已打款 5已拒绝 6已撤回
    audit_by     bigint        NOT NULL DEFAULT 0,     -- 审核管理员
    audit_at     timestamptz,
    paid_at      timestamptz,
    remark       varchar(255)  NOT NULL DEFAULT '',    -- 审核备注/拒绝原因
    pay_voucher  varchar(500)  NOT NULL DEFAULT '',    -- 打款凭证
    created_at   timestamptz   NOT NULL DEFAULT now(),
    updated_at   timestamptz   NOT NULL DEFAULT now(),
    UNIQUE (site_id, trade_no)
);
CREATE INDEX idx_withdrawal_user ON withdrawal (site_id, user_id, id DESC);
CREATE INDEX idx_withdrawal_audit ON withdrawal (site_id, status, id DESC);
COMMENT ON TABLE withdrawal IS '提现单';

-- 运营参数(走 app_config KV, 后台可改, 不用改代码)
INSERT INTO app_config (site_id, grp, key, value, remark, status) VALUES
    (1, 'withdrawal', 'withdraw_open',        'true', '提现总开关', 1),
    (1, 'withdrawal', 'withdraw_min',         '100',  '单笔最低提现金额', 1),
    (1, 'withdrawal', 'withdraw_max',         '50000','单笔最高提现金额', 1),
    (1, 'withdrawal', 'withdraw_multiple',    '10',   '提现金额需为该值的整数倍(0=不限制)', 1),
    (1, 'withdrawal', 'withdraw_fee_rate',    '2',    '提现手续费率(%)', 1),
    (1, 'withdrawal', 'withdraw_daily_limit', '3',    '每人每日提现次数上限', 1),
    (1, 'withdrawal', 'withdraw_interval_sec','10',   '两次提现最小间隔(秒)', 1)
ON CONFLICT (site_id, key) DO NOTHING;

-- +goose Down
DELETE FROM app_config WHERE site_id = 1 AND grp = 'withdrawal';
DROP TABLE IF EXISTS withdrawal;
DROP TABLE IF EXISTS bank_card;
