-- 热搜词(移植自 tianbi hotsearch): 手动权重 heat + 自动计数 search_count。
-- 排行 rank 无独立表: 从 user_collect 点赞 GROUP BY 聚合 + Redis 缓存。
-- +goose Up
CREATE TABLE hot_search (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      bigint      NOT NULL DEFAULT 1,
    keyword      varchar(64) NOT NULL,
    heat         int         NOT NULL DEFAULT 0,  -- 手动权重(运营置顶)
    search_count bigint      NOT NULL DEFAULT 0,  -- 自动搜索计数
    status       smallint    NOT NULL DEFAULT 1,  -- 1展示 0隐藏
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (site_id, keyword)
);
CREATE INDEX idx_hot_search_top ON hot_search (site_id, status, heat DESC, search_count DESC);
COMMENT ON TABLE hot_search IS '热搜词';

INSERT INTO hot_search (site_id, keyword, heat, status) VALUES
    (1, '国产', 100, 1), (1, '热血漫画', 90, 1), (1, '写真', 80, 1);

-- +goose Down
DROP TABLE IF EXISTS hot_search;
