-- 优惠券(移植自 tianbi coupons/coupons_user)。
-- 模板表 coupon_tpl(运营配置) + 用户券 user_coupon(领取时快照面值, 模板改价不影响已发放)。
-- tianbi 的坑(已修正): 自动选券的过期过滤写成 `{"gte": now}` 少了 `$`, 过期券会被选中;
-- PG 版把「有效期 + 状态 + 门槛 + 场景」四个条件全部写进 SQL, 从查询层杜绝。
-- +goose Up
CREATE TABLE coupon_tpl (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id     bigint        NOT NULL DEFAULT 1,
    name        varchar(64)   NOT NULL,
    type        smallint      NOT NULL DEFAULT 1,     -- 1抵用券(减面额) 2折扣券(打折)
    scene       smallint      NOT NULL DEFAULT 1,     -- 1充值 2内容购买 3通用
    face_value  numeric(14,2) NOT NULL DEFAULT 0,     -- 抵用券面额
    discount    int           NOT NULL DEFAULT 100,   -- 折扣券: 85 表示 85 折
    threshold   numeric(14,2) NOT NULL DEFAULT 0,     -- 使用门槛(订单金额 >= 门槛)
    max_deduct  numeric(14,2) NOT NULL DEFAULT 0,     -- 折扣券最高抵扣, 0=不封顶
    total       int           NOT NULL DEFAULT -1,    -- 发放总量, -1=不限量
    issued      int           NOT NULL DEFAULT 0,     -- 已发放
    per_limit   int           NOT NULL DEFAULT 1,     -- 每人限领, 0=不限
    expire_day  int           NOT NULL DEFAULT 7,     -- 领取后有效天数
    status      smallint      NOT NULL DEFAULT 1,     -- 1启用 0停用
    created_at  timestamptz   NOT NULL DEFAULT now(),
    updated_at  timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_coupon_tpl_list ON coupon_tpl (site_id, status, id DESC);
COMMENT ON TABLE coupon_tpl IS '优惠券模板';

CREATE TABLE user_coupon (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id     bigint        NOT NULL DEFAULT 1,
    user_id     bigint        NOT NULL,
    tpl_id      bigint        NOT NULL,
    name        varchar(64)   NOT NULL DEFAULT '',    -- 以下为领取时的模板快照
    type        smallint      NOT NULL DEFAULT 1,
    scene       smallint      NOT NULL DEFAULT 1,
    face_value  numeric(14,2) NOT NULL DEFAULT 0,
    discount    int           NOT NULL DEFAULT 100,
    threshold   numeric(14,2) NOT NULL DEFAULT 0,
    max_deduct  numeric(14,2) NOT NULL DEFAULT 0,
    status      smallint      NOT NULL DEFAULT 1,     -- 1未使用 2已使用 3已过期
    used_at     timestamptz,
    ref_id      varchar(64)   NOT NULL DEFAULT '',    -- 核销关联的业务单号
    expire_at   timestamptz   NOT NULL,
    created_at  timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_user_coupon_my ON user_coupon (site_id, user_id, status, expire_at DESC);
CREATE INDEX idx_user_coupon_tpl ON user_coupon (site_id, tpl_id, user_id);
COMMENT ON TABLE user_coupon IS '用户优惠券';

INSERT INTO coupon_tpl (site_id, name, type, scene, face_value, threshold, total, per_limit, expire_day, status)
VALUES (1, '新人满100减10', 1, 3, 10, 100, -1, 1, 30, 1);

-- +goose Down
DROP TABLE IF EXISTS user_coupon;
DROP TABLE IF EXISTS coupon_tpl;
