-- 内容购买记录(Phase 3 基建, 供 Phase 4 漫画/小说/图集/视频付费解锁复用)。
-- tianbi 对应 buyhistory 集合: (userId, objectId, mediaType) 唯一, 判断"是否已购"。
-- media_type 全局约定: 1视频 2帖子 3漫画 4小说 5图集(与 user_collect 同一套编码)。
-- +goose Up
CREATE TABLE content_purchase (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint        NOT NULL DEFAULT 1,
    user_id    bigint        NOT NULL,
    media_type smallint      NOT NULL,                -- 1视频 2帖子 3漫画 4小说 5图集
    content_id bigint        NOT NULL,
    title      varchar(128)  NOT NULL DEFAULT '',     -- 快照, 避免内容删除后记录不可读
    amount     numeric(14,2) NOT NULL DEFAULT 0,      -- 实付金币
    created_at timestamptz   NOT NULL DEFAULT now(),
    UNIQUE (site_id, user_id, media_type, content_id) -- 防重复购买(幂等的最后一道闸)
);
CREATE INDEX idx_cp_user ON content_purchase (site_id, user_id, id DESC);
CREATE INDEX idx_cp_content ON content_purchase (site_id, media_type, content_id);
COMMENT ON TABLE content_purchase IS '内容购买记录(付费解锁)';

-- +goose Down
DROP TABLE IF EXISTS content_purchase;
