-- 商品兑换(移植自 tianbi redeem): 金币兑换商品 + 兑换记录。
-- +goose Up
CREATE TABLE redeem_goods (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint        NOT NULL DEFAULT 1,
    name       varchar(64)   NOT NULL,
    cover      varchar(500)  NOT NULL DEFAULT '',
    intro      varchar(255)  NOT NULL DEFAULT '',
    cost_gold  numeric(14,2) NOT NULL DEFAULT 0,   -- 兑换所需金币
    stock      int           NOT NULL DEFAULT -1,  -- -1=不限量
    exchanged  int           NOT NULL DEFAULT 0,   -- 已兑换数
    rank       int           NOT NULL DEFAULT 0,
    status     smallint      NOT NULL DEFAULT 1,   -- 1上架 0下架
    created_at timestamptz   NOT NULL DEFAULT now(),
    updated_at timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_redeem_goods_list ON redeem_goods (site_id, status, rank DESC, id DESC);
COMMENT ON TABLE redeem_goods IS '兑换商品';

CREATE TABLE redeem_goods_order (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint        NOT NULL DEFAULT 1,
    user_id    bigint        NOT NULL,
    goods_id   bigint        NOT NULL,
    goods_name varchar(64)   NOT NULL DEFAULT '',
    cost_gold  numeric(14,2) NOT NULL DEFAULT 0,
    created_at timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_rgo_user ON redeem_goods_order (site_id, user_id, id DESC);
COMMENT ON TABLE redeem_goods_order IS '商品兑换记录';

INSERT INTO redeem_goods (site_id, name, intro, cost_gold, stock, rank, status)
VALUES (1, '7天VIP体验卡', '样板商品', 50, 100, 100, 1);

-- +goose Down
DROP TABLE IF EXISTS redeem_goods_order;
DROP TABLE IF EXISTS redeem_goods;
