-- 小说(与 00036 漫画同构; 差异只在"章节载体")。
-- Mongo → PG 的取舍:
--   * 漫画章节是图片数组(jsonb), 小说章节是整段正文 → 直接 text, 不切段不拆表;
--   * 额外维护 word_count: 章节级是本章字数, 作品级是全书总字数(章节增删时按实际行汇总, 见 syncChapterCount);
--   * is_audio 标记有声小说, 音频落在章节的 audio_url 上(同一部书可能只有部分章有音频, 故字段可空);
--   * 付费模型与漫画完全一致: is_vip / price 两态(见 shared/paywall), free_chapter 控制前 N 章免费。
-- +goose Up
CREATE TABLE novel (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       bigint        NOT NULL DEFAULT 1,
    title         varchar(128)  NOT NULL,
    author        varchar(64)   NOT NULL DEFAULT '',
    cover         varchar(500)  NOT NULL DEFAULT '',
    intro         varchar(1000) NOT NULL DEFAULT '',
    category      varchar(32)   NOT NULL DEFAULT '',   -- 分类
    tags          jsonb         NOT NULL DEFAULT '[]', -- 标签数组
    is_vip        smallint      NOT NULL DEFAULT 0,    -- 1=VIP专享(与 price 互斥)
    price         numeric(14,2) NOT NULL DEFAULT 0,    -- 金币整部价
    free_chapter  int           NOT NULL DEFAULT 1,    -- 前 N 章免费(章节序号 <= N)
    chapter_count int           NOT NULL DEFAULT 0,
    word_count    bigint        NOT NULL DEFAULT 0,    -- 全书总字数(由章节汇总, 非人工填)
    is_audio      smallint      NOT NULL DEFAULT 0,    -- 1=有声小说(章节带 audio_url)
    view_count    bigint        NOT NULL DEFAULT 0,
    buy_count     bigint        NOT NULL DEFAULT 0,
    like_count    bigint        NOT NULL DEFAULT 0,
    update_status smallint      NOT NULL DEFAULT 1,    -- 1连载 2完结
    rank          int           NOT NULL DEFAULT 0,    -- 人工权重
    status        smallint      NOT NULL DEFAULT 0,    -- 0待上架 1上架 2下架
    publish_id    bigint        NOT NULL DEFAULT 0,    -- 投稿来源用户(0=官方)
    created_at    timestamptz   NOT NULL DEFAULT now(),
    updated_at    timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_novel_list ON novel (site_id, status, rank DESC, id DESC);
CREATE INDEX idx_novel_cate ON novel (site_id, status, category);
CREATE INDEX idx_novel_tags ON novel USING GIN (tags);
COMMENT ON TABLE novel IS '小说作品';

CREATE TABLE novel_chapter (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    novel_id   bigint       NOT NULL,
    seq        int          NOT NULL,               -- 章节序号, 从 1 开始
    title      varchar(128) NOT NULL DEFAULT '',
    content    text         NOT NULL DEFAULT '',    -- 正文(整章一次性读写)
    word_count int          NOT NULL DEFAULT 0,     -- 本章字数
    audio_url  varchar(500),                        -- 有声音频; 无声小说为 NULL
    status     smallint     NOT NULL DEFAULT 1,     -- 1上架 0下架
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (site_id, novel_id, seq)
);
CREATE INDEX idx_novel_chapter ON novel_chapter (site_id, novel_id, seq);
COMMENT ON TABLE novel_chapter IS '小说章节';

-- 标题 trgm 索引(搜索用; 扩展没装则跳过)
-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm') THEN
        CREATE INDEX IF NOT EXISTS idx_novel_title_trgm ON novel USING GIN (title gin_trgm_ops);
    END IF;
END
$$;
-- +goose StatementEnd

-- 样板数据: 一部免费 + 一部付费, 便于 e2e 直接跑
INSERT INTO novel (site_id, title, author, intro, category, tags, is_vip, price, free_chapter, chapter_count, rank, status)
VALUES
    (1, '样板小说·免费篇', '佚名', '用于 e2e 的免费样板', '都市', '["都市","样板"]', 0, 0,  99, 2, 100, 1),
    (1, '样板小说·付费篇', '佚名', '用于 e2e 的付费样板', '玄幻', '["玄幻","样板"]', 0, 20, 1,  2, 90,  1);

INSERT INTO novel_chapter (site_id, novel_id, seq, title, content, status)
SELECT 1, n.id, s.seq, '第' || s.seq || '章',
       '夜色沉沉, 长街尽头的灯火忽明忽暗。他握紧手中的旧书, 知道从今夜起, 一切都不一样了。',
       1
FROM novel n CROSS JOIN (SELECT generate_series(1, 2) AS seq) s
WHERE n.site_id = 1 AND n.title LIKE '样板小说%';

-- 字数不硬编码, 按正文实测(口径与代码里的 rune 计数一致)
UPDATE novel_chapter c SET word_count = char_length(c.content)
WHERE c.site_id = 1 AND c.novel_id IN (SELECT id FROM novel WHERE site_id = 1 AND title LIKE '样板小说%');

-- 作品总字数与章节字数保持一致(与后台章节增删时的汇总口径相同)
UPDATE novel n SET word_count = (
    SELECT COALESCE(SUM(c.word_count), 0) FROM novel_chapter c
    WHERE c.site_id = n.site_id AND c.novel_id = n.id
) WHERE n.site_id = 1 AND n.title LIKE '样板小说%';

-- +goose Down
DROP TABLE IF EXISTS novel_chapter;
DROP TABLE IF EXISTS novel;
