-- UGC 投稿(用户提交内容线索, 审核通过后由运营落成正式作品)。
-- 设计取舍:
--   * 投稿只是"待处理的素材单", 不进各内容表, 所以单独一张表, 不复用 comics/photo;
--   * type 是「投稿类型」, 与 paywall 的 media_type 是两套编码, 千万别混用(见下方注释);
--   * resource 用 jsonb 存附件/外链数组: 投稿附件形态不固定(网盘链接/图片/预览图), 只整体读写;
--   * 审核字段(audit_by/audit_at/reject_reason)留痕, 便于追责与申诉。
-- +goose Up
CREATE TABLE user_publish (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       bigint        NOT NULL DEFAULT 1,
    user_id       bigint        NOT NULL,
    -- 投稿类型: 1视频 2漫画 3小说 4图集。
    -- 注意: 这与 shared/paywall 的 media_type(1视频 2帖子 3漫画 4小说 5图集) 是不同的编码,
    -- 投稿表只描述"用户想投什么", 不参与付费解锁判定, 因此不强求两者对齐。
    type          smallint      NOT NULL DEFAULT 1,
    title         varchar(128)  NOT NULL,
    intro         varchar(1000) NOT NULL DEFAULT '',
    cover         varchar(500)  NOT NULL DEFAULT '',
    resource      jsonb         NOT NULL DEFAULT '[]', -- 投稿附件/链接数组
    tags          jsonb         NOT NULL DEFAULT '[]',
    -- 0待审 1通过 2拒绝 3用户撤回(撤回不删行, 保留投稿痕迹便于统计与风控)
    status        smallint      NOT NULL DEFAULT 0,
    reject_reason varchar(255)  NOT NULL DEFAULT '',
    audit_by      bigint        NOT NULL DEFAULT 0,    -- 审核管理员ID
    audit_at      timestamptz,
    created_at    timestamptz   NOT NULL DEFAULT now(),
    updated_at    timestamptz   NOT NULL DEFAULT now()
);
-- "我的投稿"列表
CREATE INDEX idx_publish_user ON user_publish (site_id, user_id, id DESC);
-- 后台审核队列(绝大多数查询是 status=0 捞待审)
CREATE INDEX idx_publish_status ON user_publish (site_id, status, id DESC);
COMMENT ON TABLE user_publish IS '用户UGC投稿';

-- +goose Down
DROP TABLE IF EXISTS user_publish;
