-- 抽奖(移植自 tianbi lottery/lottery_prize/lottery_log)。
-- Mongo → PG 的取舍与修正:
--   * 奖品概率 odds 用「整数权重」而不是 tianbi 的百分比: 百分比要求各奖品之和恰好=100,
--     运营改一个奖品就得手动配平其余的, 极易配出「和不等于100」→ 尾部奖品永远抽不中;
--     整数权重只按前缀和取模, 增删奖品不需要动其它行。
--   * 库存 stock 沿用 redeem_goods 的约定: -1=不限量, >0=有限量, 发放走条件递减防超发。
--   * 中奖记录 lottery_history 是资金/资产变动的凭证, 与扣费写在同一个事务里(tianbi 是
--     go func 异步写, 写失败奖已经发出去了, 对不上账)。
--   * prize_addr 是本项目新增: tianbi 实物奖只能线下找客服登记地址, 这里给用户自助填写,
--     history_id 唯一约束保证一个奖只有一张收货单。
-- +goose Up
CREATE TABLE lottery_activity (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      bigint        NOT NULL DEFAULT 1,
    name         varchar(64)   NOT NULL,
    lottery_type smallint      NOT NULL DEFAULT 1,    -- 1会员日 2福利
    pay_type     smallint      NOT NULL DEFAULT 1,    -- 1仅免费次数 2金币(免费次数用完后付费)
    cost_gold    numeric(14,2) NOT NULL DEFAULT 0,    -- 单次金币价(pay_type=2 时生效)
    daily_free   int           NOT NULL DEFAULT 0,    -- 每日免费次数
    daily_limit  int           NOT NULL DEFAULT 0,    -- 每日总抽次数上限, 0=不限
    notice       text          NOT NULL DEFAULT '',   -- 活动说明(富文本)
    status       smallint      NOT NULL DEFAULT 1,    -- 1启用 0停用
    created_at   timestamptz   NOT NULL DEFAULT now(),
    updated_at   timestamptz   NOT NULL DEFAULT now()
);
-- 一个站点同一种玩法只允许一个活动: 前台按 lottery_type 取活动, 有重复就说不清取哪个。
CREATE UNIQUE INDEX uk_lottery_activity_type ON lottery_activity (site_id, lottery_type);
COMMENT ON TABLE lottery_activity IS '抽奖活动';

CREATE TABLE lottery_prize (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       bigint        NOT NULL DEFAULT 1,
    activity_id   bigint        NOT NULL,
    name          varchar(64)   NOT NULL,
    cover         varchar(500)  NOT NULL DEFAULT '',
    "desc"        varchar(255)  NOT NULL DEFAULT '',
    type          smallint      NOT NULL DEFAULT 5,   -- 1金币 2VIP天数 3优惠券 4实物 5谢谢参与
    amount        numeric(14,2) NOT NULL DEFAULT 0,   -- 金币数 / VIP天数 / 实物件数
    coupon_tpl_id bigint        NOT NULL DEFAULT 0,   -- type=3 时指向 coupon_tpl.id
    odds          int           NOT NULL DEFAULT 0,   -- 整数权重(不是百分比), <=0 表示不参与抽取
    stock         int           NOT NULL DEFAULT -1,  -- -1=不限量
    awarded       int           NOT NULL DEFAULT 0,   -- 已发出数量
    rank          int           NOT NULL DEFAULT 0,   -- 前台展示排序权重
    status        smallint      NOT NULL DEFAULT 1,   -- 1启用 0停用
    created_at    timestamptz   NOT NULL DEFAULT now(),
    updated_at    timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_lottery_prize_pool ON lottery_prize (site_id, activity_id, status);
COMMENT ON TABLE lottery_prize IS '抽奖奖品';

CREATE TABLE lottery_history (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id      bigint        NOT NULL DEFAULT 1,
    user_id      bigint        NOT NULL,
    activity_id  bigint        NOT NULL,
    lottery_type smallint      NOT NULL DEFAULT 1,
    pay_type     smallint      NOT NULL DEFAULT 1,    -- 本次消耗方式: 1免费次数 2金币
    cost_gold    numeric(14,2) NOT NULL DEFAULT 0,    -- 本次实付金币(免费次数为0)
    prize_id     bigint        NOT NULL DEFAULT 0,
    prize_name   varchar(64)   NOT NULL DEFAULT '',   -- 奖品名快照, 奖品改名不影响历史
    prize_type   smallint      NOT NULL DEFAULT 5,
    prize_amount numeric(14,2) NOT NULL DEFAULT 0,
    status       smallint      NOT NULL DEFAULT 1,    -- 1已发放 2待发货 3已发货
    remark       varchar(255)  NOT NULL DEFAULT '',
    created_at   timestamptz   NOT NULL DEFAULT now(),
    updated_at   timestamptz   NOT NULL DEFAULT now()
);
-- 每日次数统计走 (user_id, created_at); 跑马灯走 (site_id, id DESC)。
CREATE INDEX idx_lottery_history_daily ON lottery_history (site_id, user_id, created_at DESC);
CREATE INDEX idx_lottery_history_feed ON lottery_history (site_id, prize_type, id DESC);
COMMENT ON TABLE lottery_history IS '抽奖中奖记录';

CREATE TABLE prize_addr (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         bigint       NOT NULL DEFAULT 1,
    history_id      bigint       NOT NULL,
    user_id         bigint       NOT NULL,
    receiver        varchar(64)  NOT NULL DEFAULT '',
    phone           varchar(32)  NOT NULL DEFAULT '',
    address         varchar(255) NOT NULL DEFAULT '',
    delivery_status smallint     NOT NULL DEFAULT 0,  -- 0待填写 1待发货 2已发货
    express_no      varchar(64)  NOT NULL DEFAULT '',
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now()
);
-- 一条中奖记录只对应一张收货单, 唯一约束顶掉「重复提交地址生成多单」。
CREATE UNIQUE INDEX uk_prize_addr_history ON prize_addr (history_id);
CREATE INDEX idx_prize_addr_list ON prize_addr (site_id, delivery_status, id DESC);
COMMENT ON TABLE prize_addr IS '实物奖收货单';

-- 样板活动: 福利抽奖, 每天 1 次免费, 之后 10 金币一次, 每天最多 10 次。
INSERT INTO lottery_activity (site_id, name, lottery_type, pay_type, cost_gold, daily_free, daily_limit, notice, status)
VALUES (1, '福利抽奖', 2, 2, 10, 1, 10, '每日一次免费机会, 用完后 10 金币抽一次。实物奖请在中奖后填写收货地址。', 1);

-- 样板奖品: 权重合计 1000, 谢谢参与占 50%。
INSERT INTO lottery_prize (site_id, activity_id, name, "desc", type, amount, odds, stock, rank, status)
SELECT 1, a.id, v.name, v.d, v.t, v.amt, v.odds, v.stock, v.rank, 1
FROM lottery_activity a,
     (VALUES ('谢谢参与', '再接再厉', 5::smallint, 0::numeric, 500, -1, 10),
             ('10金币',   '小赚一笔', 1::smallint, 10::numeric, 300, -1, 20),
             ('100金币',  '手气不错', 1::smallint, 100::numeric, 150, -1, 30),
             ('VIP3天',   '尊享会员', 2::smallint, 3::numeric,  40, -1, 40),
             ('实物周边', '限量周边, 中奖后填写收货地址', 4::smallint, 1::numeric, 10, 5, 50)
     ) AS v(name, d, t, amt, odds, stock, rank)
WHERE a.site_id = 1 AND a.lottery_type = 2;

-- +goose Down
DROP TABLE IF EXISTS prize_addr;
DROP TABLE IF EXISTS lottery_history;
DROP TABLE IF EXISTS lottery_prize;
DROP TABLE IF EXISTS lottery_activity;
