-- AI 生成任务(统一骨架): 覆盖 tianbi 的脱衣换脸 ai / AI女友 aimate / 文生图 aitexttoimage /
-- 图生视频 aiimagetovideo / 文生小说 aitexttonovel / AI客服 —— 它们业务形态完全一致:
--   「提交任务 → 第三方异步处理 → 回调或轮询拿结果 → 计费与失败退款」。
-- tianbi 每种玩法各写一套表和一套扣费逻辑, 同样的退款 bug 要修 6 遍; 这里合并成
-- 一张 ai_task, 用 biz_type 区分玩法, 差异只落在 params/result 两个 jsonb 里。
--
-- 设计要点(为什么这么建):
--   * 供应商未定, 所以表里只留 provider / provider_task_id 两个中性字段, 不出现任何
--     具体供应商的字段名与协议细节; 换供应商只是换 provider 值 + 新增一个 adapter。
--   * task_no 是我们自己的业务单号, UNIQUE(site_id, task_no): 既是对外暴露的任务标识,
--     也是提交给供应商的幂等键(供应商重推/我们重试都靠它对齐同一笔)。
--   * client_token 是客户端自带的幂等键: 前端双击/断网重试会重复发同一个提交请求,
--     没有它就会重复建任务 + 重复扣费。这里用「部分唯一索引」在 DB 层兜底,
--     即使应用层的先查后插被并发击穿, 第二条也会被唯一约束顶掉, 钱不会扣两次。
--     空串表示客户端没传(PG 的部分索引比可空列更好用: 不用为 NULL 的比较语义纠结)。
--   * status 把「失败」和「已退款」拆成两个值(4/5): 退款是一次独立的资金动作,
--     必须能从状态本身看出"这笔钱到底退了没有", 否则重复回调时无从判断是否已补偿。
--     所有终态流转一律走「条件更新 + RowsAffected 判定」, 从 SQL 层保证只退一次。
--   * cost_gold 落在任务行上, 是退款金额的唯一依据: 模板价格后来被运营改了,
--     也必须按下单时实扣的金额退回, 不能按现价退。
-- +goose Up
CREATE TABLE ai_template (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint        NOT NULL DEFAULT 1,
    name       varchar(64)   NOT NULL,
    biz_type   smallint      NOT NULL DEFAULT 1,   -- 1换脸 2脱衣 3文生图 4图生视频 5文生小说 6AI对话
    cover      varchar(500)  NOT NULL DEFAULT '',
    preview    varchar(500)  NOT NULL DEFAULT '',  -- 效果预览图/视频
    params     jsonb         NOT NULL DEFAULT '{}'::jsonb, -- 模板预设参数(风格/尺寸/模型档位等), 与用户输入合并后交给供应商
    cost_gold  numeric(14,2) NOT NULL DEFAULT 0,   -- 该模板单次价格; 价格只认这里, 绝不接受客户端传值
    sort       int           NOT NULL DEFAULT 0,
    status     smallint      NOT NULL DEFAULT 1,   -- 1启用 0停用
    created_at timestamptz   NOT NULL DEFAULT now(),
    updated_at timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_ai_template_list ON ai_template (site_id, biz_type, status, sort DESC, id DESC);
COMMENT ON TABLE ai_template IS 'AI生成模板(玩法预设+定价)';

CREATE TABLE ai_task (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id          bigint        NOT NULL DEFAULT 1,
    user_id          bigint        NOT NULL,
    biz_type         smallint      NOT NULL DEFAULT 1,
    template_id      bigint        NOT NULL DEFAULT 0,  -- 0=不用模板(直接按 ai_default_cost 计价)
    task_no          varchar(64)   NOT NULL,            -- 业务单号, 兼作对供应商的幂等键
    client_token     varchar(64)   NOT NULL DEFAULT '', -- 客户端幂等键, 空串=未传
    params           jsonb         NOT NULL DEFAULT '{}'::jsonb, -- 用户输入(提示词/参数)
    input_url        varchar(500)  NOT NULL DEFAULT '', -- 输入素材(原图/原视频)
    cost_gold        numeric(14,2) NOT NULL DEFAULT 0,  -- 本次实扣金币, 退款按它退
    status           smallint      NOT NULL DEFAULT 1,  -- 1排队中 2处理中 3成功 4失败 5已退款 6已取消
    provider         varchar(32)   NOT NULL DEFAULT '', -- 供应商标识(中性字段, 不含任何协议细节)
    provider_task_id varchar(128)  NOT NULL DEFAULT '', -- 外部任务号, 回调/轮询按它反查本地任务
    result           jsonb         NOT NULL DEFAULT '{}'::jsonb, -- 产物: 图片/视频URL 或文本内容
    err_msg          varchar(500)  NOT NULL DEFAULT '',
    retry_count      int           NOT NULL DEFAULT 0,
    submitted_at     timestamptz,
    finished_at      timestamptz,
    created_at       timestamptz   NOT NULL DEFAULT now(),
    updated_at       timestamptz   NOT NULL DEFAULT now()
);
-- 业务单号全局唯一: 重复提交/重复回调都靠它对齐同一笔。
CREATE UNIQUE INDEX uk_ai_task_no ON ai_task (site_id, task_no);
-- 客户端幂等键: 只对"真的传了 token"的行生效, 双击提交在 DB 层就被顶掉(防重复扣费)。
CREATE UNIQUE INDEX uk_ai_task_client_token ON ai_task (site_id, user_id, client_token)
    WHERE client_token <> '';
-- 我的任务列表
CREATE INDEX idx_ai_task_user ON ai_task (site_id, user_id, id DESC);
-- 后台按状态捞单 / 运维扫超时任务
CREATE INDEX idx_ai_task_status ON ai_task (site_id, status, id DESC);
-- 回调与轮询按外部任务号反查
CREATE INDEX idx_ai_task_provider ON ai_task (site_id, provider, provider_task_id);
COMMENT ON TABLE ai_task IS 'AI生成任务(提交/回调/计费补偿)';

-- 运营参数(ON CONFLICT DO NOTHING: 迁移可重复执行, 也不覆盖运营改过的值)
INSERT INTO app_config (site_id, grp, key, value, remark, status) VALUES
    (1, 'ai', 'ai_open',            'true',       'AI功能总开关', 1),
    (1, 'ai', 'ai_default_cost',    '20',         '无模板时的单次默认价格(金币)', 1),
    (1, 'ai', 'ai_daily_limit',     '20',         '每人每日AI任务数上限, <=0 表示不限', 1),
    (1, 'ai', 'ai_callback_secret', '"changeme"', 'AI回调验签密钥, 上线必须改', 1)
ON CONFLICT (site_id, key) DO NOTHING;

-- 样板模板: 换脸 / 文生图 / 文生小说 各一(价格各不相同, 便于验证"价格只认服务端")。
INSERT INTO ai_template (site_id, name, biz_type, cover, preview, params, cost_gold, sort, status) VALUES
    (1, '经典换脸',   1, '', '', '{"model":"face-v1","quality":"hd"}'::jsonb,        30, 30, 1),
    (1, '文生图·写实', 3, '', '', '{"style":"realistic","size":"1024x1024"}'::jsonb,  20, 20, 1),
    (1, '文生小说·都市', 5, '', '', '{"genre":"urban","length":2000}'::jsonb,         10, 10, 1);

-- +goose Down
DROP TABLE IF EXISTS ai_task;
DROP TABLE IF EXISTS ai_template;
DELETE FROM app_config WHERE site_id = 1 AND key IN ('ai_open', 'ai_default_cost', 'ai_daily_limit', 'ai_callback_secret');
