-- 子后台「动漫管理」：视频表加 kind 区分，分类独立成表，标签复用 tag.content_type=3。
-- +goose Up
ALTER TABLE video ADD COLUMN IF NOT EXISTS kind smallint NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_video_kind_status_sort ON video (kind, status, sort DESC, id DESC);
COMMENT ON COLUMN video.kind IS '0视频 2动漫(对齐媒资中心 kind)';

CREATE TABLE cartoon_category (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    name       varchar(32) NOT NULL,
    kind       smallint    NOT NULL DEFAULT 0,
    rank       int         NOT NULL DEFAULT 0,
    status     smallint    NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (site_id, name)
);
CREATE INDEX idx_cartoon_category_repo ON cartoon_category (site_id, status, rank DESC, id DESC);
COMMENT ON TABLE cartoon_category IS '动漫分类(H5 顶栏 + 作品分类)';

INSERT INTO cartoon_category (site_id, name, kind, rank, status) VALUES
    (1, '最新',   1, 100, 1),
    (1, '推荐',   2, 90,  1),
    (1, '动漫榜', 3, 80,  1),
    (1, '番剧',   0, 70,  1),
    (1, '剧场版', 0, 60,  1);

UPDATE admin_permission
SET sort = 22
WHERE is_menu = 1 AND parent_id = 0 AND name = '漫画管理' AND sort <= 21;

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT 0, '动漫管理', '/cartoon', '', '', 'lucide:tv', 1, 0, 0, 21
WHERE NOT EXISTS (
    SELECT 1 FROM admin_permission
    WHERE is_menu = 1 AND parent_id = 0 AND name = '动漫管理' AND route_url = '/cartoon'
);

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '动漫列表', '/cartoon/list', 'cartoon/index', '', 'lucide:clapperboard', 1, 0, 0, 1
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '动漫管理' AND p.route_url = '/cartoon'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '动漫列表' AND x.route_url = '/cartoon/list'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('动漫列表',   '/backend/videos',                   'GET',    1),
    ('新增动漫',   '/backend/videos',                   'POST',   2),
    ('编辑动漫',   '/backend/videos/{id}',              'PUT',    3),
    ('删除动漫',   '/backend/videos/{id}',              'DELETE', 4),
    ('动漫上下架', '/backend/videos/{id}/status',       'PUT',    5),
    ('媒资同步',   '/backend/videos/sync-media',        'POST',  12),
    ('媒资库列表', '/backend/media-assets',             'GET',   13),
    ('选用媒资',   '/backend/media-assets/{id}/pick',   'POST',  14)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '动漫列表' AND m.route_url = '/cartoon/list'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '动漫分类', '/cartoon/category', 'content/cartoon-category', '', 'lucide:folders', 1, 0, 0, 2
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '动漫管理' AND p.route_url = '/cartoon'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '动漫分类' AND x.route_url = '/cartoon/category'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('分类列表', '/backend/cartoon-categories',      'GET',    1),
    ('新增分类', '/backend/cartoon-categories',      'POST',   2),
    ('编辑分类', '/backend/cartoon-categories/{id}', 'PUT',    3),
    ('删除分类', '/backend/cartoon-categories/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '动漫分类' AND m.route_url = '/cartoon/category'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '动漫标签', '/cartoon/tag', 'content/cartoon-tag', '', 'lucide:tags', 1, 0, 0, 3
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '动漫管理' AND p.route_url = '/cartoon'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '动漫标签' AND x.route_url = '/cartoon/tag'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('标签列表', '/backend/tag',      'GET',    1),
    ('新增标签', '/backend/tag',      'POST',   2),
    ('编辑标签', '/backend/tag/{id}', 'PUT',    3),
    ('删除标签', '/backend/tag/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '动漫标签' AND m.route_url = '/cartoon/tag'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0
  AND parent_id IN (
      SELECT id FROM admin_permission
      WHERE is_menu = 1 AND (
          (name = '动漫列表' AND route_url = '/cartoon/list')
          OR (name = '动漫分类' AND route_url = '/cartoon/category')
          OR (name = '动漫标签' AND route_url = '/cartoon/tag')
      )
  );
DELETE FROM admin_permission
WHERE is_menu = 1 AND (
    (name = '动漫列表' AND route_url = '/cartoon/list')
    OR (name = '动漫分类' AND route_url = '/cartoon/category')
    OR (name = '动漫标签' AND route_url = '/cartoon/tag')
    OR (name = '动漫管理' AND route_url = '/cartoon' AND parent_id = 0)
);
DROP TABLE IF EXISTS cartoon_category;
DROP INDEX IF EXISTS idx_video_kind_status_sort;
ALTER TABLE video DROP COLUMN IF EXISTS kind;
