-- 视频分类 + 视频标签菜单。分类新表; 标签复用 tag.content_type=1(影片)。
-- +goose Up
CREATE TABLE video_category (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    name       varchar(32) NOT NULL,
    kind       smallint    NOT NULL DEFAULT 0,
    rank       int         NOT NULL DEFAULT 0,
    status     smallint    NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (site_id, name)
);
CREATE INDEX idx_video_category_repo ON video_category (site_id, status, rank DESC, id DESC);
COMMENT ON TABLE video_category IS '视频分类(H5 顶栏 + 作品分类)';

INSERT INTO video_category (site_id, name, kind, rank, status) VALUES
    (1, '最新',   1, 100, 1),
    (1, '推荐',   2, 90,  1),
    (1, '视频榜', 3, 80,  1),
    (1, '电影',   0, 70,  1),
    (1, '短剧',   0, 60,  1),
    (1, '综艺',   0, 50,  1);

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '视频分类', '/video/category', 'content/video-category', '', 'lucide:folders', 1, 0, 0, 2
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '视频管理'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '视频分类' AND x.route_url = '/video/category'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('分类列表', '/backend/video-categories',      'GET',    1),
    ('新增分类', '/backend/video-categories',      'POST',   2),
    ('编辑分类', '/backend/video-categories/{id}', 'PUT',    3),
    ('删除分类', '/backend/video-categories/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '视频分类' AND m.route_url = '/video/category'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '视频标签', '/video/tag', 'content/video-tag', '', 'lucide:tags', 1, 0, 0, 3
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '视频管理'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '视频标签' AND x.route_url = '/video/tag'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('标签列表', '/backend/tag',      'GET',    1),
    ('新增标签', '/backend/tag',      'POST',   2),
    ('编辑标签', '/backend/tag/{id}', 'PUT',    3),
    ('删除标签', '/backend/tag/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '视频标签' AND m.route_url = '/video/tag'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0
  AND parent_id IN (
      SELECT id FROM admin_permission
      WHERE is_menu = 1 AND (
          (name = '视频分类' AND route_url = '/video/category')
          OR (name = '视频标签' AND route_url = '/video/tag')
      )
  );
DELETE FROM admin_permission
WHERE is_menu = 1 AND (
    (name = '视频分类' AND route_url = '/video/category')
    OR (name = '视频标签' AND route_url = '/video/tag')
);
DROP TABLE IF EXISTS video_category;
