-- 漫画分类: 控制 H5 二次元页顶部分类栏, 同时作为作品 category 的可选项。
-- kind: 0 普通分类(按名称筛作品)  1 新更  2 推荐  3 榜单(后三种只占栏位, 不给作品打标)。
-- +goose Up
CREATE TABLE comics_category (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    name       varchar(32) NOT NULL,
    kind       smallint    NOT NULL DEFAULT 0,
    rank       int         NOT NULL DEFAULT 0,
    status     smallint    NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (site_id, name)
);
CREATE INDEX idx_comics_category_repo ON comics_category (site_id, status, rank DESC, id DESC);
COMMENT ON TABLE comics_category IS '漫画分类(H5 顶栏 + 作品分类)';

INSERT INTO comics_category (site_id, name, kind, rank, status) VALUES
    (1, '新更',   1, 100, 1),
    (1, '推荐',   2, 90,  1),
    (1, '漫画榜', 3, 80,  1),
    (1, '韩漫',   0, 70,  1),
    (1, '日漫',   0, 60,  1),
    (1, '同人',   0, 50,  1),
    (1, '国漫',   0, 40,  1);

-- 挂到「漫画管理」一级菜单下, 不写死 parent_id(库里 id 可能因手工建菜单对不上)
INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '漫画分类', '/comics/category', 'content/comics-category', '', 'lucide:folders', 1, 0, 0, 2
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '漫画管理'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '漫画分类' AND x.route_url = '/comics/category'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('分类列表', '/backend/comics-categories',     'GET',    1),
    ('新增分类', '/backend/comics-categories',     'POST',   2),
    ('编辑分类', '/backend/comics-categories/{id}', 'PUT',    3),
    ('删除分类', '/backend/comics-categories/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '漫画分类' AND m.route_url = '/comics/category'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0 AND route_url IN (
    '/backend/comics-categories',
    '/backend/comics-categories/{id}'
);
DELETE FROM admin_permission
WHERE is_menu = 1 AND name = '漫画分类' AND route_url = '/comics/category';
DROP TABLE IF EXISTS comics_category;
