-- 一级菜单「社区管理」改名为「帖子管理」；二级：帖子列表 / 帖子分类 / 帖子模块。
-- 帖子分类表对齐 cartoon_category。
-- +goose Up
CREATE TABLE post_category (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    name       varchar(32) NOT NULL,
    kind       smallint    NOT NULL DEFAULT 0,
    rank       int         NOT NULL DEFAULT 0,
    status     smallint    NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (site_id, name)
);
CREATE INDEX idx_post_category_repo ON post_category (site_id, status, rank DESC, id DESC);
COMMENT ON TABLE post_category IS '帖子分类(H5 顶栏 + 作品分类)';

INSERT INTO post_category (site_id, name, kind, rank, status) VALUES
    (1, '最新',     1, 100, 1),
    (1, '推荐',     2, 90,  1),
    (1, '热帖',     3, 80,  1),
    (1, '活动专区', 0, 70,  1),
    (1, '日常专区', 0, 60,  1);

-- 先改二级「帖子管理」→「帖子列表」，再改一级「社区管理」→「帖子管理」。
UPDATE admin_permission
SET name = '帖子列表'
WHERE is_menu = 1 AND name = '帖子管理' AND route_url = '/community/post';

UPDATE admin_permission
SET name = '帖子管理'
WHERE is_menu = 1 AND parent_id = 0 AND name = '社区管理' AND route_url = '/community';

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '帖子分类', '/community/category', 'community/post-category', '', 'lucide:folders', 1, 0, 0, 2
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '帖子管理' AND p.route_url = '/community'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '帖子分类' AND x.route_url = '/community/category'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('分类列表', '/backend/post-categories',      'GET',    1),
    ('新增分类', '/backend/post-categories',      'POST',   2),
    ('编辑分类', '/backend/post-categories/{id}', 'PUT',    3),
    ('删除分类', '/backend/post-categories/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '帖子分类' AND m.route_url = '/community/category'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

UPDATE admin_permission
SET sort = 3
WHERE is_menu = 1 AND name = '帖子模块' AND route_url = '/community/section';

UPDATE admin_role r
SET permissions = trim(both ',' from r.permissions || ',' || ids.joined)
FROM (
    SELECT string_agg(p.id::text, ',') AS joined
    FROM admin_permission p
    WHERE (p.is_menu = 1 AND p.name = '帖子分类' AND p.route_url = '/community/category')
       OR p.parent_id IN (
           SELECT id FROM admin_permission
           WHERE is_menu = 1 AND name = '帖子分类' AND route_url = '/community/category'
       )
) ids
WHERE r.code <> 'superadmin'
  AND ids.joined IS NOT NULL
  AND (
      (',' || r.permissions || ',') LIKE '%,130,%'
      OR EXISTS (
          SELECT 1 FROM admin_permission m
          WHERE m.is_menu = 1 AND m.name = '帖子列表' AND m.route_url = '/community/post'
            AND (',' || r.permissions || ',') LIKE '%,' || m.id::text || ',%'
      )
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0
  AND parent_id IN (
      SELECT id FROM admin_permission
      WHERE is_menu = 1 AND name = '帖子分类' AND route_url = '/community/category'
  );
DELETE FROM admin_permission
WHERE is_menu = 1 AND name = '帖子分类' AND route_url = '/community/category';

UPDATE admin_permission
SET sort = 2
WHERE is_menu = 1 AND name = '帖子模块' AND route_url = '/community/section';

UPDATE admin_permission
SET name = '社区管理'
WHERE is_menu = 1 AND parent_id = 0 AND name = '帖子管理' AND route_url = '/community';

UPDATE admin_permission
SET name = '帖子管理'
WHERE is_menu = 1 AND name = '帖子列表' AND route_url = '/community/post';

DROP TABLE IF EXISTS post_category;
