-- 签到配置: 阶梯奖励补积分/里程碑, 全局补签与 VIP 组, 运营菜单。
-- +goose Up
ALTER TABLE checkin_reward
    ADD COLUMN IF NOT EXISTS label varchar(32) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS points bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS is_milestone smallint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ms_points bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ms_gold bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ms_vip_days int NOT NULL DEFAULT 0;
COMMENT ON COLUMN checkin_reward.points IS '普通签到积分';
COMMENT ON COLUMN checkin_reward.is_milestone IS '1=里程碑, 当天只发里程碑奖励';
COMMENT ON COLUMN checkin_reward.ms_points IS '里程碑积分';
COMMENT ON COLUMN checkin_reward.ms_gold IS '里程碑金币';
COMMENT ON COLUMN checkin_reward.ms_vip_days IS '里程碑VIP天数';

ALTER TABLE user_checkin
    ADD COLUMN IF NOT EXISTS reward_points bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reward_vip_days int NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS checkin_config (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       bigint       NOT NULL DEFAULT 1,
    makeup_points int          NOT NULL DEFAULT 5,
    makeup_limit  int          NOT NULL DEFAULT 3,
    makeup_desc   varchar(64)  NOT NULL DEFAULT '',
    vip_group_id  bigint       NOT NULL DEFAULT 0,
    updated_at    timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_checkin_config_site ON checkin_config (site_id);
COMMENT ON TABLE checkin_config IS '签到全局配置(补签/VIP组)';

INSERT INTO checkin_config (site_id, makeup_points, makeup_limit, makeup_desc, vip_group_id)
VALUES (1, 5, 3, '每月可补签3次，每次消耗5积分', 0)
ON CONFLICT (site_id) DO NOTHING;

-- 已有 1/2/3/5/7 天补上积分与标签, 并补齐 1-15 天。
UPDATE checkin_reward SET
    label = '第' || day_num || '天',
    points = CASE day_num
        WHEN 1 THEN 10 WHEN 2 THEN 18 WHEN 3 THEN 26 WHEN 5 THEN 42 WHEN 7 THEN 50
        ELSE 10 + (day_num - 1) * 8 END,
    gold = CASE WHEN gold = 0 THEN day_num ELSE gold END
WHERE site_id = 1 AND user_type = 0;

INSERT INTO checkin_reward (site_id, day_num, user_type, label, points, gold, vip_days, is_milestone, status)
SELECT 1, d, 0, '第' || d || '天',
       CASE WHEN d = 15 THEN 150 ELSE 10 + (d - 1) * 8 END,
       d,
       CASE WHEN d = 7 THEN 3 WHEN d = 14 THEN 3 ELSE 0 END,
       0, 1
FROM generate_series(1, 15) AS d
WHERE NOT EXISTS (
    SELECT 1 FROM checkin_reward r
    WHERE r.site_id = 1 AND r.user_type = 0 AND r.day_num = d
);

UPDATE checkin_reward SET
    is_milestone = 1, ms_points = 22, ms_gold = 12, ms_vip_days = 12, vip_days = 0
WHERE site_id = 1 AND user_type = 0 AND day_num = 8;

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '签到配置', '/ops/checkin', 'ops/checkin', '', 'lucide:calendar-check', 1, 0, 0, 10
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '运营管理'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '签到配置' AND x.route_url = '/ops/checkin'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('签到配置读取', '/backend/checkin/config',  'GET', 1),
    ('签到配置保存', '/backend/checkin/config',  'PUT', 2),
    ('签到奖励读取', '/backend/checkin/rewards', 'GET', 3),
    ('签到奖励保存', '/backend/checkin/rewards', 'PUT', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '签到配置' AND m.route_url = '/ops/checkin'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

UPDATE admin_role r
SET permissions = trim(both ',' from r.permissions || ',' || ids.joined)
FROM (
    SELECT string_agg(p.id::text, ',') AS joined
    FROM admin_permission p
    WHERE (p.is_menu = 1 AND p.name = '签到配置' AND p.route_url = '/ops/checkin')
       OR p.parent_id IN (
           SELECT id FROM admin_permission
           WHERE is_menu = 1 AND name = '签到配置' AND route_url = '/ops/checkin'
       )
) ids
WHERE r.code <> 'superadmin'
  AND ids.joined IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM admin_permission m
      WHERE m.is_menu = 1 AND m.name = '运营管理'
        AND (',' || r.permissions || ',') LIKE '%,' || m.id::text || ',%'
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0 AND parent_id IN (
    SELECT id FROM admin_permission WHERE is_menu = 1 AND name = '签到配置' AND route_url = '/ops/checkin'
);
DELETE FROM admin_permission
WHERE is_menu = 1 AND name = '签到配置' AND route_url = '/ops/checkin';
DROP TABLE IF EXISTS checkin_config;
ALTER TABLE user_checkin
    DROP COLUMN IF EXISTS reward_points,
    DROP COLUMN IF EXISTS reward_vip_days;
ALTER TABLE checkin_reward
    DROP COLUMN IF EXISTS label,
    DROP COLUMN IF EXISTS points,
    DROP COLUMN IF EXISTS is_milestone,
    DROP COLUMN IF EXISTS ms_points,
    DROP COLUMN IF EXISTS ms_gold,
    DROP COLUMN IF EXISTS ms_vip_days;
