-- 漫画首页楼层模块: 标题/样式/标签检索由运营配置, 与「漫画分类」解耦。
-- style: 1=1大2小横图 2=2小横图 3=1大横图 4=2竖图 5=竖图横滑 6=横图横滑 7=竖图3X3
-- 检索条件暂按标签(tag_ids), 无标签则回落最新。
-- +goose Up
CREATE TABLE comics_module (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    name       varchar(64)  NOT NULL,
    position   varchar(32)  NOT NULL DEFAULT 'comic_home',
    style      smallint     NOT NULL DEFAULT 7,
    icon       smallint     NOT NULL DEFAULT 1,
    tag_ids    jsonb        NOT NULL DEFAULT '[]',
    size       int          NOT NULL DEFAULT 9,
    rank       int          NOT NULL DEFAULT 0,
    status     smallint     NOT NULL DEFAULT 1,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_comics_module_repo ON comics_module (site_id, position, status, rank DESC, id DESC);
COMMENT ON TABLE comics_module IS '漫画首页运营模块(标题+样式+标签检索)';
COMMENT ON COLUMN comics_module.style IS '1=1大2小横图 2=2小横图 3=1大横图 4=2竖图 5=竖图横滑 6=横图横滑 7=竖图3X3';
COMMENT ON COLUMN comics_module.icon IS '1最新 2星星 3火';
COMMENT ON COLUMN comics_module.tag_ids IS '检索标签ID列表, 空则按最新';
COMMENT ON COLUMN comics_module.position IS '展示位置, 目前 comic_home=漫画首页';

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '漫画模块', '/comics/module', 'content/comics-module', '', 'lucide:layout-grid', 1, 0, 0, 4
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '漫画管理'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '漫画模块' AND x.route_url = '/comics/module'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('模块列表', '/backend/comics-modules',     'GET',    1),
    ('新增模块', '/backend/comics-modules',     'POST',   2),
    ('编辑模块', '/backend/comics-modules/{id}', 'PUT',    3),
    ('删除模块', '/backend/comics-modules/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '漫画模块' AND m.route_url = '/comics/module'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

UPDATE admin_role r
SET permissions = trim(both ',' from r.permissions || ',' || ids.joined)
FROM (
    SELECT string_agg(p.id::text, ',') AS joined
    FROM admin_permission p
    WHERE (p.is_menu = 1 AND p.name = '漫画模块' AND p.route_url = '/comics/module')
       OR p.parent_id IN (
           SELECT id FROM admin_permission
           WHERE is_menu = 1 AND name = '漫画模块' AND route_url = '/comics/module'
       )
) ids
WHERE r.code <> 'superadmin'
  AND ids.joined IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM admin_permission m
      WHERE m.is_menu = 1 AND m.name = '漫画管理'
        AND (',' || r.permissions || ',') LIKE '%,' || m.id::text || ',%'
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0
  AND parent_id IN (
      SELECT id FROM admin_permission
      WHERE is_menu = 1 AND name = '漫画模块' AND route_url = '/comics/module'
  );
DELETE FROM admin_permission
WHERE is_menu = 1 AND name = '漫画模块' AND route_url = '/comics/module';
DROP TABLE IF EXISTS comics_module;
