-- 官方社群: 前台「官方社群」入口对应的群链接管理。
-- 同时把运营管理下「推广应用」改名为「福利应用」, 与 H5 文案对齐。
-- +goose Up

CREATE TABLE official_group (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint        NOT NULL DEFAULT 1,
    name       varchar(64)   NOT NULL,
    intro      varchar(255)  NOT NULL DEFAULT '',
    avatar     varchar(500)  NOT NULL DEFAULT '',
    link       varchar(500)  NOT NULL DEFAULT '',
    platform   varchar(32)   NOT NULL DEFAULT '',
    rank       int           NOT NULL DEFAULT 0,
    status     smallint      NOT NULL DEFAULT 1,
    created_at timestamptz   NOT NULL DEFAULT now(),
    updated_at timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_official_group_list ON official_group (site_id, status, rank DESC, id DESC);
COMMENT ON TABLE official_group IS '官方社群';

INSERT INTO official_group (site_id, name, intro, link, platform, rank, status) VALUES
    (1, '官方交流群', '进群领取最新福利与公告', 'https://t.me/', 'telegram', 100, 1);

UPDATE admin_permission
SET name = '福利应用', icon = 'lucide:app-window'
WHERE is_menu = 1 AND name = '推广应用' AND route_url = '/ops/application';

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '官方社群', '/ops/group', 'ops/group', '', 'lucide:users', 1, 0, 0, 9
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '运营管理'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '官方社群' AND x.route_url = '/ops/group'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('社群列表', '/backend/group',        'GET',    1),
    ('新增社群', '/backend/group',        'POST',   2),
    ('编辑社群', '/backend/group/{id}',   'PUT',    3),
    ('删除社群', '/backend/group/{id}',   'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '官方社群' AND m.route_url = '/ops/group'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

UPDATE admin_role r
SET permissions = trim(both ',' from r.permissions || ',' || ids.joined)
FROM (
    SELECT string_agg(p.id::text, ',') AS joined
    FROM admin_permission p
    WHERE (p.is_menu = 1 AND p.name = '官方社群' AND p.route_url = '/ops/group')
       OR p.parent_id IN (
           SELECT id FROM admin_permission
           WHERE is_menu = 1 AND name = '官方社群' AND route_url = '/ops/group'
       )
) ids
WHERE r.code <> 'superadmin'
  AND ids.joined IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM admin_permission m
      WHERE m.is_menu = 1 AND m.name = '运营管理'
        AND (',' || r.permissions || ',') LIKE '%,' || m.id::text || ',%'
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0 AND parent_id IN (
    SELECT id FROM admin_permission
    WHERE is_menu = 1 AND name = '官方社群' AND route_url = '/ops/group'
);
DELETE FROM admin_permission
WHERE is_menu = 1 AND name = '官方社群' AND route_url = '/ops/group';
UPDATE admin_permission
SET name = '推广应用'
WHERE is_menu = 1 AND name = '福利应用' AND route_url = '/ops/application';
DROP TABLE IF EXISTS official_group;
