-- 互动消息(评论/点赞)，与 sys_message 站内信分离。
-- 评论逐条；点赞按「目标 + 北京时间自然日」用 agg_key 聚合。
-- +goose Up
CREATE TABLE interact_message (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         bigint       NOT NULL DEFAULT 1,
    user_id         bigint       NOT NULL,
    channel         varchar(16)  NOT NULL,
    sub_type        varchar(32)  NOT NULL,
    actor_id        bigint       NOT NULL DEFAULT 0,
    actor_ids       jsonb        NOT NULL DEFAULT '[]',
    like_count      int          NOT NULL DEFAULT 0,
    media_type      smallint     NOT NULL DEFAULT 2,
    content_id      bigint       NOT NULL DEFAULT 0,
    object_title    text         NOT NULL DEFAULT '',
    target_type     varchar(16)  NOT NULL DEFAULT 'comment',
    comment_id      bigint       NOT NULL DEFAULT 0,
    root_comment_id bigint       NOT NULL DEFAULT 0,
    snippet         text         NOT NULL DEFAULT '',
    is_read         smallint     NOT NULL DEFAULT 0,
    agg_key         varchar(128) NOT NULL DEFAULT '',
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_interact_user_channel ON interact_message (site_id, user_id, channel, updated_at DESC);
CREATE INDEX idx_interact_unread ON interact_message (site_id, user_id, channel, is_read);
CREATE UNIQUE INDEX uk_interact_agg_key ON interact_message (site_id, agg_key) WHERE agg_key <> '';
COMMENT ON TABLE interact_message IS '互动消息(评论逐条/点赞日聚合)';

-- +goose Down
DROP TABLE IF EXISTS interact_message;
