-- 视频/动漫首页运营模块, 对齐漫画模块。检索暂按标签。
-- +goose Up
CREATE TABLE video_module (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    name       varchar(64)  NOT NULL,
    position   varchar(32)  NOT NULL DEFAULT 'video_home',
    style      smallint     NOT NULL DEFAULT 2,
    icon       smallint     NOT NULL DEFAULT 1,
    tag_ids    jsonb        NOT NULL DEFAULT '[]',
    size       int          NOT NULL DEFAULT 6,
    rank       int          NOT NULL DEFAULT 0,
    status     smallint     NOT NULL DEFAULT 1,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_video_module_repo ON video_module (site_id, position, status, rank DESC, id DESC);
COMMENT ON TABLE video_module IS '视频首页运营模块(标题+样式+标签检索)';

CREATE TABLE cartoon_module (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    name       varchar(64)  NOT NULL,
    position   varchar(32)  NOT NULL DEFAULT 'cartoon_home',
    style      smallint     NOT NULL DEFAULT 2,
    icon       smallint     NOT NULL DEFAULT 1,
    tag_ids    jsonb        NOT NULL DEFAULT '[]',
    size       int          NOT NULL DEFAULT 6,
    rank       int          NOT NULL DEFAULT 0,
    status     smallint     NOT NULL DEFAULT 1,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_cartoon_module_repo ON cartoon_module (site_id, position, status, rank DESC, id DESC);
COMMENT ON TABLE cartoon_module IS '动漫首页运营模块(标题+样式+标签检索)';

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '视频模块', '/video/module', 'content/video-module', '', 'lucide:layout-grid', 1, 0, 0, 4
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '视频管理'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '视频模块' AND x.route_url = '/video/module'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('模块列表', '/backend/video-modules',     'GET',    1),
    ('新增模块', '/backend/video-modules',     'POST',   2),
    ('编辑模块', '/backend/video-modules/{id}', 'PUT',    3),
    ('删除模块', '/backend/video-modules/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '视频模块' AND m.route_url = '/video/module'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '动漫模块', '/cartoon/module', 'content/cartoon-module', '', 'lucide:layout-grid', 1, 0, 0, 4
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '动漫管理'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '动漫模块' AND x.route_url = '/cartoon/module'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('模块列表', '/backend/cartoon-modules',     'GET',    1),
    ('新增模块', '/backend/cartoon-modules',     'POST',   2),
    ('编辑模块', '/backend/cartoon-modules/{id}', 'PUT',    3),
    ('删除模块', '/backend/cartoon-modules/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '动漫模块' AND m.route_url = '/cartoon/module'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

UPDATE admin_role r
SET permissions = trim(both ',' from r.permissions || ',' || ids.joined)
FROM (
    SELECT string_agg(p.id::text, ',') AS joined
    FROM admin_permission p
    WHERE (p.is_menu = 1 AND p.name IN ('视频模块', '动漫模块') AND p.route_url IN ('/video/module', '/cartoon/module'))
       OR p.parent_id IN (
           SELECT id FROM admin_permission
           WHERE is_menu = 1 AND name IN ('视频模块', '动漫模块')
             AND route_url IN ('/video/module', '/cartoon/module')
       )
) ids
WHERE r.code <> 'superadmin'
  AND ids.joined IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM admin_permission m
      WHERE m.is_menu = 1 AND m.name IN ('视频管理', '动漫管理')
        AND (',' || r.permissions || ',') LIKE '%,' || m.id::text || ',%'
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0 AND parent_id IN (
    SELECT id FROM admin_permission
    WHERE is_menu = 1 AND name IN ('视频模块', '动漫模块')
      AND route_url IN ('/video/module', '/cartoon/module')
);
DELETE FROM admin_permission
WHERE is_menu = 1 AND name IN ('视频模块', '动漫模块')
  AND route_url IN ('/video/module', '/cartoon/module');
DROP TABLE IF EXISTS cartoon_module;
DROP TABLE IF EXISTS video_module;
