-- 金刚区基础配置：按展示位置（漫画/动漫/视频等）投放图标入口。
-- +goose Up
CREATE TABLE kingkong_item (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint       NOT NULL DEFAULT 1,
    name       varchar(32)  NOT NULL,
    icon_url   varchar(500) NOT NULL DEFAULT '',
    open_mode  varchar(16)  NOT NULL DEFAULT 'block',
    link       varchar(500) NOT NULL DEFAULT '',
    app_link   varchar(500) NOT NULL DEFAULT '',
    position   varchar(32)  NOT NULL DEFAULT 'comics',
    sort       int          NOT NULL DEFAULT 0,
    status     smallint     NOT NULL DEFAULT 1,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_kingkong_item_repo ON kingkong_item (site_id, position, status, sort DESC, id DESC);
COMMENT ON TABLE kingkong_item IS '金刚区入口(图标+跳转+展示位置)';
COMMENT ON COLUMN kingkong_item.open_mode IS '打开方式: block=模块 list=列表 douyin=抖音流';
COMMENT ON COLUMN kingkong_item.link IS 'H5 跳转: 预设 code / 自定义地址; 空则走模块';
COMMENT ON COLUMN kingkong_item.app_link IS 'Native App 优先地址; 空则按跳转类型映射';
COMMENT ON COLUMN kingkong_item.position IS 'comics=漫画 cartoon=动漫 movie=视频 novel=小说 short=短剧';
COMMENT ON COLUMN kingkong_item.sort IS '数值越大越靠前';
COMMENT ON COLUMN kingkong_item.status IS '1开启 0关闭';

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT 0, '金刚区', '/kingkong', '', '', 'lucide:gem', 1, 0, 0, 85
WHERE NOT EXISTS (
    SELECT 1 FROM admin_permission x
    WHERE x.is_menu = 1 AND x.parent_id = 0 AND x.name = '金刚区' AND x.route_url = '/kingkong'
);

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '基础配置', '/kingkong/config', 'ops/kingkong-config', '', 'lucide:sliders', 1, 0, 0, 1
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '金刚区' AND p.route_url = '/kingkong'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '基础配置' AND x.route_url = '/kingkong/config'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('金刚区列表', '/backend/kingkong-items',      'GET',    1),
    ('新增金刚区', '/backend/kingkong-items',      'POST',   2),
    ('编辑金刚区', '/backend/kingkong-items/{id}', 'PUT',    3),
    ('删除金刚区', '/backend/kingkong-items/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '基础配置' AND m.route_url = '/kingkong/config'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

UPDATE admin_role r
SET permissions = trim(both ',' from r.permissions || ',' || ids.joined)
FROM (
    SELECT string_agg(p.id::text, ',') AS joined
    FROM admin_permission p
    WHERE (p.is_menu = 1 AND p.name = '金刚区' AND p.route_url = '/kingkong')
       OR (p.is_menu = 1 AND p.name = '基础配置' AND p.route_url = '/kingkong/config')
       OR p.parent_id IN (
           SELECT id FROM admin_permission
           WHERE is_menu = 1 AND name = '基础配置' AND route_url = '/kingkong/config'
       )
) ids
WHERE r.code <> 'superadmin'
  AND ids.joined IS NOT NULL;

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0
  AND parent_id IN (
      SELECT id FROM admin_permission
      WHERE is_menu = 1 AND name = '基础配置' AND route_url = '/kingkong/config'
  );
DELETE FROM admin_permission
WHERE is_menu = 1 AND name = '基础配置' AND route_url = '/kingkong/config';
DELETE FROM admin_permission
WHERE is_menu = 1 AND parent_id = 0 AND name = '金刚区' AND route_url = '/kingkong';
DROP TABLE IF EXISTS kingkong_item;
