-- 子后台「抖音管理」：video.kind=3，分类独立成表，标签复用 tag.content_type=2。
-- 不做抖音模块：H5 是全屏竖滑信息流，不是视频首页那种楼层海报墙。
-- +goose Up
COMMENT ON COLUMN video.kind IS '0视频 2动漫 3抖音(对齐媒资中心 kind)';

CREATE TABLE douyin_category (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint      NOT NULL DEFAULT 1,
    name       varchar(32) NOT NULL,
    kind       smallint    NOT NULL DEFAULT 0,
    rank       int         NOT NULL DEFAULT 0,
    status     smallint    NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (site_id, name)
);
CREATE INDEX idx_douyin_category_repo ON douyin_category (site_id, status, rank DESC, id DESC);
COMMENT ON TABLE douyin_category IS '抖音分类(作品打标；关注/喜欢是用户行为流，不要做成分类)';

-- 插在「视频管理」正下方
WITH v AS (
    SELECT sort FROM admin_permission
    WHERE is_menu = 1 AND parent_id = 0 AND name = '视频管理' AND route_url = '/video'
    LIMIT 1
)
UPDATE admin_permission p
SET sort = p.sort + 1
FROM v
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.sort > v.sort;

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT 0, '抖音管理', '/douyin', '', '', 'lucide:smartphone', 1, 0, 0, p.sort + 1
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '视频管理' AND p.route_url = '/video'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission
      WHERE is_menu = 1 AND parent_id = 0 AND name = '抖音管理' AND route_url = '/douyin'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '抖音列表', '/douyin/list', 'douyin/index', '', 'lucide:clapperboard', 1, 0, 0, 1
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '抖音管理' AND p.route_url = '/douyin'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '抖音列表' AND x.route_url = '/douyin/list'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('抖音列表',   '/backend/videos',                   'GET',    1),
    ('新增抖音',   '/backend/videos',                   'POST',   2),
    ('编辑抖音',   '/backend/videos/{id}',              'PUT',    3),
    ('删除抖音',   '/backend/videos/{id}',              'DELETE', 4),
    ('抖音上下架', '/backend/videos/{id}/status',       'PUT',    5),
    ('媒资同步',   '/backend/videos/sync-media',        'POST',  12),
    ('媒资库列表', '/backend/media-assets',             'GET',   13),
    ('选用媒资',   '/backend/media-assets/{id}/pick',   'POST',  14)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '抖音列表' AND m.route_url = '/douyin/list'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '抖音分类', '/douyin/category', 'content/douyin-category', '', 'lucide:folders', 1, 0, 0, 2
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '抖音管理' AND p.route_url = '/douyin'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '抖音分类' AND x.route_url = '/douyin/category'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('分类列表', '/backend/douyin-categories',      'GET',    1),
    ('新增分类', '/backend/douyin-categories',      'POST',   2),
    ('编辑分类', '/backend/douyin-categories/{id}', 'PUT',    3),
    ('删除分类', '/backend/douyin-categories/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '抖音分类' AND m.route_url = '/douyin/category'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '抖音标签', '/douyin/tag', 'content/douyin-tag', '', 'lucide:tags', 1, 0, 0, 3
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '抖音管理' AND p.route_url = '/douyin'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '抖音标签' AND x.route_url = '/douyin/tag'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('标签列表', '/backend/tag',      'GET',    1),
    ('新增标签', '/backend/tag',      'POST',   2),
    ('编辑标签', '/backend/tag/{id}', 'PUT',    3),
    ('删除标签', '/backend/tag/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '抖音标签' AND m.route_url = '/douyin/tag'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

-- 已有视频管理权限的非超管角色，一并放开抖音菜单
UPDATE admin_role r
SET permissions = r.permissions || ',' || ids.joined
FROM (
    SELECT string_agg(p.id::text, ',') AS joined
    FROM admin_permission p
    WHERE (p.is_menu = 1 AND p.name IN ('抖音管理', '抖音列表', '抖音分类', '抖音标签')
           AND p.route_url IN ('/douyin', '/douyin/list', '/douyin/category', '/douyin/tag'))
       OR p.parent_id IN (
           SELECT id FROM admin_permission
           WHERE is_menu = 1 AND name IN ('抖音列表', '抖音分类', '抖音标签')
             AND route_url IN ('/douyin/list', '/douyin/category', '/douyin/tag')
       )
) ids
WHERE r.code <> 'superadmin'
  AND ids.joined IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM admin_permission m
      WHERE m.is_menu = 1 AND m.name = '视频管理' AND m.route_url = '/video'
        AND (',' || r.permissions || ',') LIKE '%,' || m.id::text || ',%'
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0
  AND parent_id IN (
      SELECT id FROM admin_permission
      WHERE is_menu = 1 AND (
          (name = '抖音列表' AND route_url = '/douyin/list')
          OR (name = '抖音分类' AND route_url = '/douyin/category')
          OR (name = '抖音标签' AND route_url = '/douyin/tag')
      )
  );
DELETE FROM admin_permission
WHERE is_menu = 1 AND (
    (name = '抖音列表' AND route_url = '/douyin/list')
    OR (name = '抖音分类' AND route_url = '/douyin/category')
    OR (name = '抖音标签' AND route_url = '/douyin/tag')
    OR (name = '抖音管理' AND route_url = '/douyin' AND parent_id = 0)
);
DROP TABLE IF EXISTS douyin_category;
COMMENT ON COLUMN video.kind IS '0视频 2动漫(对齐媒资中心 kind)';
