-- 运营管理「轮播配置」：按位置投放漫画/动漫/视频/小说首页轮播。
-- +goose Up

CREATE TABLE banner (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint        NOT NULL DEFAULT 1,
    position   varchar(32)   NOT NULL,
    title      varchar(128)  NOT NULL DEFAULT '',
    cover_url  varchar(500)  NOT NULL DEFAULT '',
    link       varchar(500)  NOT NULL DEFAULT '',
    rank       int           NOT NULL DEFAULT 0,
    status     smallint      NOT NULL DEFAULT 1,
    created_at timestamptz   NOT NULL DEFAULT now(),
    updated_at timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_banner_list ON banner (site_id, position, status, rank DESC, id DESC);
COMMENT ON TABLE banner IS '首页轮播';

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '轮播配置', '/ops/banner', 'ops/banner', '', 'lucide:images', 1, 0, 0, 2
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '运营管理'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '轮播配置' AND x.route_url = '/ops/banner'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('轮播列表', '/backend/banner',      'GET',    1),
    ('新增轮播', '/backend/banner',      'POST',   2),
    ('编辑轮播', '/backend/banner/{id}', 'PUT',    3),
    ('删除轮播', '/backend/banner/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '轮播配置' AND m.route_url = '/ops/banner'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

UPDATE admin_role r
SET permissions = trim(both ',' from r.permissions || ',' || ids.joined)
FROM (
    SELECT string_agg(p.id::text, ',') AS joined
    FROM admin_permission p
    WHERE (p.is_menu = 1 AND p.name = '轮播配置' AND p.route_url = '/ops/banner')
       OR p.parent_id IN (
           SELECT id FROM admin_permission
           WHERE is_menu = 1 AND name = '轮播配置' AND route_url = '/ops/banner'
       )
) ids
WHERE r.code <> 'superadmin'
  AND ids.joined IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM admin_permission m
      WHERE m.is_menu = 1 AND m.name = '运营管理'
        AND (',' || r.permissions || ',') LIKE '%,' || m.id::text || ',%'
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0 AND parent_id IN (
    SELECT id FROM admin_permission
    WHERE is_menu = 1 AND name = '轮播配置' AND route_url = '/ops/banner'
);
DELETE FROM admin_permission
WHERE is_menu = 1 AND name = '轮播配置' AND route_url = '/ops/banner';
DROP TABLE IF EXISTS banner;
