-- 子后台「渠道管理」：推广渠道主表 + 菜单。
-- 用户归属仍写 users.channel_name；本表校验 source 是否存在且启用。
-- 与邀请/分享无关：分享只走 ?invite=，渠道只走 ?source=。
-- +goose Up

CREATE TABLE promo_channel (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint        NOT NULL DEFAULT 1,
    code       varchar(32)   NOT NULL,
    name       varchar(64)   NOT NULL DEFAULT '',
    remark     varchar(255)  NOT NULL DEFAULT '',
    status     smallint      NOT NULL DEFAULT 1,
    created_at timestamptz   NOT NULL DEFAULT now(),
    updated_at timestamptz   NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_promo_channel_site_code ON promo_channel (site_id, lower(code));
CREATE INDEX idx_promo_channel_list ON promo_channel (site_id, status, id DESC);
COMMENT ON TABLE promo_channel IS '推广渠道（H5/APP 的 source）';

INSERT INTO admin_permission (parent_id, name, route_url, component, method, icon, is_menu, hide_in_menu, affix_tab, sort)
SELECT p.id, '渠道管理', '/user/channel', 'user/channel', '', 'lucide:git-branch', 1, 0, 0, 6
FROM admin_permission p
WHERE p.is_menu = 1 AND p.parent_id = 0 AND p.name = '用户管理'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.is_menu = 1 AND x.name = '渠道管理' AND x.route_url = '/user/channel'
  )
LIMIT 1;

INSERT INTO admin_permission (parent_id, name, route_url, method, is_menu, sort)
SELECT m.id, v.name, v.route_url, v.method, 0, v.sort
FROM admin_permission m
CROSS JOIN (VALUES
    ('渠道列表', '/backend/channels',      'GET',    1),
    ('新增渠道', '/backend/channels',      'POST',   2),
    ('编辑渠道', '/backend/channels/{id}', 'PUT',    3),
    ('删除渠道', '/backend/channels/{id}', 'DELETE', 4)
) AS v(name, route_url, method, sort)
WHERE m.is_menu = 1 AND m.name = '渠道管理' AND m.route_url = '/user/channel'
  AND NOT EXISTS (
      SELECT 1 FROM admin_permission x
      WHERE x.parent_id = m.id AND x.route_url = v.route_url AND x.method = v.method AND x.is_menu = 0
  );

UPDATE admin_role r
SET permissions = trim(both ',' from r.permissions || ',' || ids.joined)
FROM (
    SELECT string_agg(p.id::text, ',') AS joined
    FROM admin_permission p
    WHERE (p.is_menu = 1 AND p.name = '渠道管理' AND p.route_url = '/user/channel')
       OR p.parent_id IN (
           SELECT id FROM admin_permission
           WHERE is_menu = 1 AND name = '渠道管理' AND route_url = '/user/channel'
       )
) ids
WHERE r.code <> 'superadmin'
  AND ids.joined IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM admin_permission m
      WHERE m.is_menu = 1 AND m.name = '用户管理'
        AND (',' || r.permissions || ',') LIKE '%,' || m.id::text || ',%'
  );

SELECT setval(pg_get_serial_sequence('admin_permission', 'id'),
              (SELECT MAX(id) FROM admin_permission));

-- +goose Down
DELETE FROM admin_permission
WHERE is_menu = 0 AND parent_id IN (
    SELECT id FROM admin_permission
    WHERE is_menu = 1 AND name = '渠道管理' AND route_url = '/user/channel'
);
DELETE FROM admin_permission
WHERE is_menu = 1 AND name = '渠道管理' AND route_url = '/user/channel';
DROP TABLE IF EXISTS promo_channel;
