// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// chatConversationDao is the data access object for the table chat_conversation.
// You can define custom methods on it to extend its functionality as needed.
type chatConversationDao struct {
	*internal.ChatConversationDao
}

var (
	// ChatConversation is a globally accessible object for table chat_conversation operations.
	ChatConversation = chatConversationDao{internal.NewChatConversationDao()}
)

// Add your custom methods and functionality below.
