// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// rechargeOrderDao is the data access object for the table recharge_order.
// You can define custom methods on it to extend its functionality as needed.
type rechargeOrderDao struct {
	*internal.RechargeOrderDao
}

var (
	// RechargeOrder is a globally accessible object for table recharge_order operations.
	RechargeOrder = rechargeOrderDao{internal.NewRechargeOrderDao()}
)

// Add your custom methods and functionality below.
