// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// rechargePackageDao is the data access object for the table recharge_package.
// You can define custom methods on it to extend its functionality as needed.
type rechargePackageDao struct {
	*internal.RechargePackageDao
}

var (
	// RechargePackage is a globally accessible object for table recharge_package operations.
	RechargePackage = rechargePackageDao{internal.NewRechargePackageDao()}
)

// Add your custom methods and functionality below.
