// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// siteDao is the data access object for the table site.
// You can define custom methods on it to extend its functionality as needed.
type siteDao struct {
	*internal.SiteDao
}

var (
	// Site is a globally accessible object for table site operations.
	Site = siteDao{internal.NewSiteDao()}
)

// Add your custom methods and functionality below.
