// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// userBalanceLogDao is the data access object for the table user_balance_log.
// You can define custom methods on it to extend its functionality as needed.
type userBalanceLogDao struct {
	*internal.UserBalanceLogDao
}

var (
	// UserBalanceLog is a globally accessible object for table user_balance_log operations.
	UserBalanceLog = userBalanceLogDao{internal.NewUserBalanceLogDao()}
)

// Add your custom methods and functionality below.
