// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// userCodeDao is the data access object for the table user_code.
// You can define custom methods on it to extend its functionality as needed.
type userCodeDao struct {
	*internal.UserCodeDao
}

var (
	// UserCode is a globally accessible object for table user_code operations.
	UserCode = userCodeDao{internal.NewUserCodeDao()}
)

// Add your custom methods and functionality below.
