// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// userShareLogDao is the data access object for the table user_share_log.
// You can define custom methods on it to extend its functionality as needed.
type userShareLogDao struct {
	*internal.UserShareLogDao
}

var (
	// UserShareLog is a globally accessible object for table user_share_log operations.
	UserShareLog = userShareLogDao{internal.NewUserShareLogDao()}
)

// Add your custom methods and functionality below.
