// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// userSignDao is the data access object for the table user_sign.
// You can define custom methods on it to extend its functionality as needed.
type userSignDao struct {
	*internal.UserSignDao
}

var (
	// UserSign is a globally accessible object for table user_sign operations.
	UserSign = userSignDao{internal.NewUserSignDao()}
)

// Add your custom methods and functionality below.
