// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// userTaskLogDao is the data access object for the table user_task_log.
// You can define custom methods on it to extend its functionality as needed.
type userTaskLogDao struct {
	*internal.UserTaskLogDao
}

var (
	// UserTaskLog is a globally accessible object for table user_task_log operations.
	UserTaskLog = userTaskLogDao{internal.NewUserTaskLogDao()}
)

// Add your custom methods and functionality below.
