// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// userCodeLogDao is the data access object for the table user_code_log.
// You can define custom methods on it to extend its functionality as needed.
type userCodeLogDao struct {
	*internal.UserCodeLogDao
}

var (
	// UserCodeLog is a globally accessible object for table user_code_log operations.
	UserCodeLog = userCodeLogDao{internal.NewUserCodeLogDao()}
)

// Add your custom methods and functionality below.
