// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// userFollowDao is the data access object for the table user_follow.
// You can define custom methods on it to extend its functionality as needed.
type userFollowDao struct {
	*internal.UserFollowDao
}

var (
	// UserFollow is a globally accessible object for table user_follow operations.
	UserFollow = userFollowDao{internal.NewUserFollowDao()}
)

// Add your custom methods and functionality below.
