// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// vipLogDao is the data access object for the table vip_log.
// You can define custom methods on it to extend its functionality as needed.
type vipLogDao struct {
	*internal.VipLogDao
}

var (
	// VipLog is a globally accessible object for table vip_log operations.
	VipLog = vipLogDao{internal.NewVipLogDao()}
)

// Add your custom methods and functionality below.
