// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/JarvanDante/my_service/internal/dao/internal"
)

// vipPackageDao is the data access object for the table vip_package.
// You can define custom methods on it to extend its functionality as needed.
type vipPackageDao struct {
	*internal.VipPackageDao
}

var (
	// VipPackage is a globally accessible object for table vip_package operations.
	VipPackage = vipPackageDao{internal.NewVipPackageDao()}
)

// Add your custom methods and functionality below.
